image:
  tag: 7.17.3

master:
  replicaCount: 1
  persistence:
    size: 2Gi
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 25m
      memory: 256Mi
coordinating:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 25m
      memory: 256Mi
data:
  replicaCount: 2
  heapSize: 512m
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 1024Mi
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
    existingClaim: ""
    existingVolume: ""