version: '3'

services:
  routing-api:
     image: ${ROUTING_API_IMAGE_NAME}
     build:
       context: .
       dockerfile: routing-api-dockerfile.yml
       args:
         MAVEN_IMAGE_NAME: ${BASE_ROUTING_API_IMAGE_NAME}
     environment:
       - SERVICE_BASE_PATH=${ROUTING_API_FQDN}
       - DATA_API_HOST=data-api.${KUBERNETES_DATA_API_NAMESPACE}.svc.cluster.local
       - DEFAULT_ADAPTER_HOST=default-adapter.${KUBERNETES_DEFAULT_ADAPTER_NAMESPACE}.svc.cluster.local
       - ADAPTER_PROTOCOL=https
       - GENERIC_ADAPTER_FQDN=${GENERIC_ADAPTER_FQDN}
     ports:
       - '8082:8082'
     labels:
       - 'kompose.image-pull-secret=${GITLAB_IMAGE_PULL_SECRET_NAME}'
       - 'kompose.service.type=clusterip'
 #    networks:
 #      - web-nw

#networks:
#  web-nw: