version: '3'

services:
  routing-api:
     image: ${ROUTING_API_IMAGE_NAME}
     build:
       context: .
       dockerfile: routing-api-dockerfile.yml
       args:
         MAVEN_IMAGE_NAME: ${BASE_ROUTING_API_IMAGE_NAME}
     environment:
       - SERVICE_BASE_PATH=${ROUTING_API_FQDN}
       - DATA_API_HOST=data-api.data-api-${CI_COMMIT_REF_SLUG}-${LANDSCAPE}.svc.cluster.local
       - DEFAULT_ADAPTER_HOST=default-adapter.default-adapter-${CI_COMMIT_REF_SLUG}-${LANDSCAPE}.svc.cluster.local
       - GENERIC_ADAPTER_HOST=generic-adapter.generic-adapter-${CI_COMMIT_REF_SLUG}-${LANDSCAPE}.svc.cluster.local
       - MAAS_API_CACHE_HOST=redis.redis-${CI_COMMIT_REF_SLUG}-${LANDSCAPE}.svc.cluster.local
       - MAAS_API_CACHE_PORT=6379
       - MAAS_API_CACHE_KEYS_PREFIX=${MAAS_API_CACHE_KEYS_PREFIX}
       - MAAS_API_CACHE_PASSWORD=${MAAS_API_CACHE_PASSWORD}
     ports:
       - '8082:8082'
     labels:
       - 'kompose.image-pull-secret=${GITLAB_IMAGE_PULL_SECRET_NAME}'
       - 'kompose.service.type=clusterip'
 #    networks:
 #      - web-nw

#networks:
#  web-nw: