apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cache-manager-cert
spec:
  dnsNames:
    - '*.${landscape_subdomain}'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ${CLUSTER_ISSUER}
  secretName: ${SECRET_NAME}
