version: '3'

services:
  request-relay:
     image: ${REQUEST_RELAY_IMAGE_NAME}
     build:
       context: .
       dockerfile: request-relay-dockerfile.yml
       args:
         MAVEN_IMAGE_NAME: ${BASE_REQUEST_RELAY_IMAGE_NAME}
     ports:
       - '8083'
     environment:
       - SERVICE_BASE_PATH=${REQUEST_RELAY_FQDN}
     labels:
       - 'kompose.image-pull-secret=${GITLAB_IMAGE_PULL_SECRET_NAME}'
       - 'kompose.service.type=clusterip'
 #    networks:
 #      - web-nw

networks:
  web-nw: