server:
  port: 8081
  shutdown: "graceful"
  servlet:
    context-path: /v1


springdoc:
  api-docs:
    path: /data-api
  swagger-ui:
    path: /api-docs.html


logging:
  level:
    org:
      springframework: INFO
      springframework.security: INFO
      springframework.web: INFO
      springframework.scheduling.concurrent: WARN
    root: INFO


spring:
  application:
    name: data-api
  lifecycle:
    timeout-per-shutdown-phase: "10s"
  profiles:
    active: test
  data:
    rest:
      base-path: #/v1
      detection-strategy: all

---

spring:
  profiles: test
security:
  disabled: true

---

spring:
  profiles: prod
security:
  disabled: false

