server:
  port: 8081
  shutdown: "graceful"
  servlet:
    context-path: /v1


springdoc:
  api-docs:
    path: /data-api
  swagger-ui:
    path: /api-docs.html


logging:
  level:
    org:
      springframework: INFO
      springframework.security: INFO
      springframework.web: INFO
      springframework.scheduling.concurrent: WARN
    com:
      gateway: DEBUG
    root: INFO


spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: data-api
  lifecycle:
    timeout-per-shutdown-phase: "10s"
  profiles:
    active: test
  data:
    rest:
      base-path: #/v1
      detection-strategy: all
  redis:
    ssl: ${MAAS_API_CACHE_SSL:false}
    password: ${MAAS_API_CACHE_PASSWORD:IWsEcFGJA0acrgHQjhnSxzZsyjnKepwFIj+UCS0ZP8I=}
    host: ${MAAS_API_CACHE_HOST:localhost}
    port: ${MAAS_API_CACHE_PORT:6379}
    connection-timeout: 30
    keys:
      prefix: ${MAAS_API_CACHE_KEYS_PREFIX:dev-}
    repositories:
      enabled: 'false'
  cache:
    type: redis

appli:
  use:
    cache: true
---

spring:
  profiles: test
security:
  disabled: true

---

spring:
  profiles: prod
security:
  disabled: false

