services:
  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kompose.image-pull-secret: ${PROXY_HANDOVER_IMAGE_PULL_SECRET_NAME}
        kompose.service.type: clusterip
        kubernetes.io/ingress.class: traefik
        app: internal-service
      labels:
        io.kompose.service: api
        app.gateway.com/service-type: internal-service
      name: api
    spec:
      ports:
        - name: "8080"
          port: 8080
          targetPort: 8080
      selector:
        io.kompose.service: api
      type: ClusterIP
    status:
      loadBalancer: {}

networkPolicies:
  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kubernetes.io/ingress.class: traefik
      name: deny-internal-services-nw
    spec:
      podSelector: { }
      policyTypes:
        - Ingress
  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kubernetes.io/ingress.class: traefik
      name: ingress-internal-policy
    spec:
      podSelector:
        matchLabels:
          visibility: external
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  com.mcm.maas.internal: "true"
        - from:
            - namespaceSelector:
                matchLabels:
                  com.mcm.maas.apim: "true"
              podSelector:
                matchLabels:
                  app.kubernetes.io/component: gateway

deployments:
  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kompose.image-pull-secret: ${PROXY_HANDOVER_IMAGE_PULL_SECRET_NAME}
        kompose.service.type: clusterip
        kubernetes.io/ingress.class: traefik
      labels:
        io.kompose.service: api
      name: api
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: api
      strategy: {}
      template:
        metadata:
          annotations:
            app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
            app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
            kompose.image-pull-secret: ${PROXY_HANDOVER_IMAGE_PULL_SECRET_NAME}
            kompose.service.type: clusterip
            kubernetes.io/ingress.class: traefik
          labels:
            io.kompose.service: api
            visibility: external
        spec:
          containers:
            env:
              DATA_API_HOST: data-api.data-api-${BASE_KUBE_NAMESPACE_WITH_BRANCH}.svc.cluster.local
              ROUTING_API_HOST: routing-api.routing-api-${BASE_KUBE_NAMESPACE_WITH_BRANCH}.svc.cluster.local
              SERVICE_BASE_PATH: ${API_FQDN}
              MAAS_API_CACHE_SSL: true
              MAAS_API_CACHE_HOST: ${MAAS_API_CACHE_HOST}
              MAAS_API_CACHE_PORT: ${MAAS_API_CACHE_PORT}
              MAAS_API_CACHE_KEYS_PREFIX: "${MAAS_API_CACHE_KEYS_PREFIX}"
              MAAS_API_CACHE_PASSWORD: "${MAAS_API_CACHE_PASSWORD}"
            image: ${API_IMAGE_NAME}
            name: api
            ports:
              - containerPort: 8080
            resources: {}
          imagePullSecrets:
            - name: ${PROXY_HANDOVER_IMAGE_PULL_SECRET_NAME}
          restartPolicy: Always
    status: {}

middlewares:
  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kubernetes.io/ingress.class: traefik
      name: api-headers-middleware
    spec:
      headers:
        customRequestHeaders:
          X-Forwarded-Port: "443"
          X-Forwarded-Proto: https

  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kubernetes.io/ingress.class: traefik
      name: api-inflightreq-middleware
    spec:
      inFlightReq:
        amount: 100

#  - metadata:
#      annotations:
#        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
#        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
#        kubernetes.io/ingress.class: traefik
#      name: api-ratelimit-middleware
#    spec:
#      rateLimit:
#        average: 30
#        burst: 50
#        period: 1m
#        sourceCriterion:
#          ipStrategy:
#            depth: 2

ingressRoutes:
  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kubernetes.io/ingress.class: traefik
      name: api
    spec:
      entryPoints:
        - web
      routes:
        - kind: Rule
          match: Host(`${API_FQDN}`)
          middlewares:
            - name: api-headers-middleware
 #           - name: api-ratelimit-middleware
            - name: api-inflightreq-middleware
          services:
            - kind: Service
              name: api
              port: 8080
