#apim:
jdbc:
  driver: https://jdbc.postgresql.org/download/postgresql-42.2.23.jar
  url: jdbc:postgresql://${GRAVITEE_DATABASE_SERVER}/${GRAVITEE_DATABASE_NAME}
  username: ${GRAVITEE_DATABASE_USER_NAME}
  password: ${GRAVITEE_DATABASE_USER_PWD}
management:
  type: jdbc
ratelimit:
  type: jdbc
jwtSecret: ${GRAVITEE_JWT_SECRET_TOKEN}

services:
  core:
    http:
      enabled: false

inMemoryAuth:
  enabled: true
  allowEmailInSearchResults: false
  passwordEncodingAlgo: bcrypt

adminAccountEnable: true
adminPasswordBcrypt: ${GRAVITEE_INMEMORY_BCRYPT_ADMIN_PASSWORD}
adminEmail: mcm_admin_gw@moncomptemobilite.org
adminFirstName:
adminLastName:

extraInMemoryUsers: |
  


## https://docs.gravitee.io/apim/3.x/apim_how_to_configuration.html#step_3_update_the_jwt_secret
#jwt:
#  secret: muOJ2G1trcbheu5_3t4v33_S3cr3t
#  # 2 days delay
#  expire-after: 172800
es:
  enabled: true
  cluster: elasticsearch
  index: gravitee
  # If the details for security are entered
  # authentication will be provided for the
  # elastic search cluster
  # https://docs.gravitee.io/apim_installguide_repositories_elasticsearch.html#management_api_configuration
  index_mode: daily # Index mode normal (daily index) vs ILM (managed by ILM)
  security:
    username: elastic
    password: ${ELASTIC_PASSWORD}
    enabled: ${ELASTIC_SECURED}
  endpoints:
    - http://elasticsearch.elasticsearch-${BASE_KUBE_NAMESPACE_WITH_BRANCH}.svc.cluster.local:9200
  lifecycle:
    enabled: false
    policyPropertyName: index.lifecycle.name   #for openDistro, use 'opendistro.index_state_management.policy_id' instead of 'index.lifecycle.name'
    policies:
      health: hot_delete_health # ILM policy for the gravitee-health-* indexes
      monitor: hot_delete_monitor # ILM policy for the gravitee-monitor-* indexes
      request: hot_delete_request # ILM policy for the gravitee-request-* indexes
      log: hot_delete_log # ILM policy for the gravitee-log-* indexes
      # http:
      # timeout: 10000
  ssl:
    enabled: false
  pipeline:
    plugins:
      ingest: geoip, user_agent # geoip and user_agent plugins are enabled by default




portal:
  image:
    repository: graviteeio/apim-portal-ui
    tag: 3.19.1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetAverageUtilization: 70
    targetMemoryAverageUtilization: 50
  ingress:
    enabled: false
    path: /
    hosts:
      - ${APIM_PORTAL_FQDN}
  deployment:
    labels: { "visibility": "external" }

ui:
  title: Management UI
  managementTitle: API Management Std MaaS | Mon Compte Mobilité
  portal:
    apikeyHeader: x-api-key
    analytics:
      enabled: true
  image:
    repository: graviteeio/apim-management-ui
    tag: 3.19.1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
  ingress:
    enabled: false
    path: /
    hosts:
      - ${APIM_CONSOLE_FQDN}
  companyName: Mon Compte Mobilité
  documentationLink: https://github.com/fabmob/mcm-gateway
  deployment:
    labels: { "visibility": "external" }

api:
  #properties:
  #  encryption:
  #    secret: ${GRAVITEE_JWT_SECRET_TOKEN}
  image:
    repository: graviteeio/apim-management-api
    tag: 3.19.1
  http:
    client:
      timeout: 30000
    services:
      core:
        http:
          enabled: "false"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetAverageUtilization: 70
    targetMemoryAverageUtilization: 50
  resources:
    requests:
      cpu: 500m
      memory: 128Mi
  reporters:
    file:
      enabled: true
      endpoints:
        - http://elasticsearch.elasticsearch-${BASE_KUBE_NAMESPACE_WITH_BRANCH}.svc.cluster.local:9200
      output: json
      request:
        include:
          - "*"
  logging:
    debug: true
    stdout:
      json: false
      encoderPattern: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file:
      enabled: true
      rollingPolicy: |
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <!-- daily rollover -->
            <fileNamePattern>${gravitee.management.log.dir}/gravitee_%d{yyyy-MM-dd}.log</fileNamePattern>
            <!-- keep 30 days' worth of history -->
            <maxHistory>30</maxHistory>
        </rollingPolicy>
      encoderPattern: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n%n"
    graviteeLevel: ${LOG_LEVEL_GRAVITEE}
    jettyLevel: INFO
  ingress:
    management:
      enabled: false
      path: /management
      hosts:
        - ${APIM_FQDN}
    portal:
      enabled: false
      path: /portal
      hosts:
        - ${APIM_FQDN}
  user:
    login:
      # Create a default application when user connects to the portal for the very first time (default true)
      defaultApplication: false
  deployment:
    labels: { "visibility": "external" }
    extraEnvs:
      - name: gravitee_user_password_policy_pattern
        value: ^(?:(?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))(?!.*(.)\1{2,})[A-Za-z0-9!~<>,;:_\-=?*+#."'&§`£€%°()\\\|\[\]\-\$\^\@\/]{8,32}$
      - name: gravitee_api_properties_encryption_secret
        value: ${GRAVITEE_API_SECRET_TOKEN}

gateway:
  image:
    repository: graviteeio/apim-gateway
    tag: 3.19.1
  policy:
    api-key:
      header: X-API-KEY
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetAverageUtilization: 70
    targetMemoryAverageUtilization: 50
  services:
    core:
      http:
        enabled: "false"
  resources:
    requests:
      cpu: 500m
      memory: 128Mi
  logging:
    graviteeLevel: ${LOG_LEVEL_GRAVITEE}
    debug: true
  ingress:
    enabled: false
    metadata:
      name: gateway-ingress
    path: /
    hosts:
      - ${APIM_GATEWAY_FQDN}
    #tls:
    #  - hosts:
    #      - ${APIM_GATEWAY_FQDN}
    #    secretName: gateway-tls-certs
  reporters:
    file:
      enabled: true
      endpoints:
        - http://elasticsearch.elasticsearch-${BASE_KUBE_NAMESPACE_WITH_BRANCH}.svc.cluster.local:9200
      output: json
      request:
        include:
          - "*"
      #log:
      #  exclude: "*"
      #node:
      #  exclude: "*"
      #healthcheck:
      #  exclude: "*"
  deployment:
    labels: { "visibility": "external" }
    extraEnvs:
      - name: gravitee_api_properties_encryption_secret
        value: ${GRAVITEE_API_SECRET_TOKEN}
analytics:
  type: elasticsearch
  elasticsearch:
    endpoints:
      - http://elasticsearch.elasticsearch-${BASE_KUBE_NAMESPACE_WITH_BRANCH}.svc.cluster.local:9200



smtp:
  enabled: true
  host: ${GRAVITEE_SMTP_HOST}
  port: ${GRAVITEE_SMTP_PORT}
  from: ${GRAVITEE_SMTP_FROM}
  username: ${GRAVITEE_SMTP_USERNAME}
  password: ${GRAVITEE_SMTP_PASSWORD}
  subject: "${GRAVITEE_SMTP_SUBJECT_PATTERN}"
  properties:
    auth: true
    starttlsEnable: false
    ssl.trust: smtp.sendgrid.net

notifiers:
  smtp:
    enabled: true
    host: ${email.host}
    subject: ${email.subject}
    port: ${email.port}
    from: ${email.from}
    username: ${email.username}
    password: ${email.password}