services:
  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kompose.image-pull-secret: ${PROXY_HANDOVER_IMAGE_PULL_SECRET_NAME}
        kompose.service.type: clusterip
        kubernetes.io/ingress.class: traefik
      labels:
        io.kompose.service: routing-api
        app.gateway.com/service-type: internal-service
      name: routing-api
    spec:
      ports:
        - name: "8082"
          port: 8082
          targetPort: 8082
      selector:
        io.kompose.service: routing-api
      type: ClusterIP
    status:
      loadBalancer: {}

networkPolicies:
  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kubernetes.io/ingress.class: traefik
      name: deny-internal-services-nw
    spec:
      podSelector: { }
      policyTypes:
        - Ingress
  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kubernetes.io/ingress.class: traefik
      name: internal-services-nw
    spec:
      podSelector:
        matchLabels:
          visibility: internal
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  com.mcm.maas.internal: "true"
        - from:
            - namespaceSelector:
                matchLabels:
                  name: monitoring

deployments:
  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kompose.image-pull-secret: ${PROXY_HANDOVER_IMAGE_PULL_SECRET_NAME}
        kompose.service.type: clusterip
        kubernetes.io/ingress.class: traefik
      labels:
        io.kompose.service: routing-api
      name: routing-api
    spec:
      replicas: 2
      selector:
        matchLabels:
          io.kompose.service: routing-api
      strategy: {}
      template:
        metadata:
          annotations:
            app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
            app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
            kompose.image-pull-secret: ${PROXY_HANDOVER_IMAGE_PULL_SECRET_NAME}
            kompose.service.type: clusterip
            kubernetes.io/ingress.class: traefik
          labels:
            io.kompose.service: routing-api
            visibility: internal
        spec:
          containers:
            env:
              DATA_API_HOST: data-api.data-api-${BASE_KUBE_NAMESPACE_WITH_BRANCH}.svc.cluster.local
              DEFAULT_ADAPTER_HOST: default-adapter.default-adapter-${BASE_KUBE_NAMESPACE_WITH_BRANCH}.svc.cluster.local
              GENERIC_ADAPTER_HOST: generic-adapter.generic-adapter-${BASE_KUBE_NAMESPACE_WITH_BRANCH}.svc.cluster.local
              SERVICE_BASE_PATH: ${ROUTING_API_FQDN}
              MAAS_API_CACHE_SSL: true
              MAAS_API_CACHE_HOST: ${MAAS_API_CACHE_HOST}
              MAAS_API_CACHE_PORT: ${MAAS_API_CACHE_PORT}
              MAAS_API_CACHE_KEYS_PREFIX: "${MAAS_API_CACHE_KEYS_PREFIX}"
              MAAS_API_CACHE_PASSWORD: "${MAAS_API_CACHE_PASSWORD}"
              DATA_API_CONTEXT_PATH: /dataapi/v1
              USE_CACHE: false
              LOG_LEVEL_SPRING: ${LOG_LEVEL_SPRING}
              LOG_LEVEL_GATEWAY: ${LOG_LEVEL_GATEWAY}
              ELASTIC_APM_SERVICE_NAME: routing-api
              ELASTIC_APM_APPLICATION_PACKAGES: com.gateway,org.springframework
              ELASTIC_APM_SERVER_URL: http://apm-server.elasticsearch-${BASE_KUBE_NAMESPACE_WITH_BRANCH}.svc.cluster.local:8200
              ELASTIC_APM_ENVIRONMENT: ${LANDSCAPE_ENV}
              GATEWAY_TIMEOUT: ${GATEWAY_TIMEOUT}
            image: ${ROUTING_API_IMAGE_NAME}
            name: routing-api
            ports:
              - containerPort: 8082
            resources: {}
          imagePullSecrets:
            - name: ${PROXY_HANDOVER_IMAGE_PULL_SECRET_NAME}
          restartPolicy: Always
    status: {}

middlewares:
  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kubernetes.io/ingress.class: traefik
      name: routing-api-headers-middleware
    spec:
      headers:
        customRequestHeaders:
          X-Forwarded-Port: "443"
          X-Forwarded-Proto: https

  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kubernetes.io/ingress.class: traefik
      name: routing-api-inflightreq-middleware
    spec:
      inFlightReq:
        amount: 100

#  - metadata:
#      annotations:
#        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
#        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
#        kubernetes.io/ingress.class: traefik
#      name: routing-api-ratelimit-middleware
#    spec:
#      rateLimit:
#        average: 30
#        burst: 50
#        period: 1m
#        sourceCriterion:
#          ipStrategy:
#            depth: 2

ingressRoutes:
  - metadata:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        kubernetes.io/ingress.class: traefik
      name: routing-api
    spec:
      entryPoints:
        - web
      routes:
        - kind: Rule
          match: Host(`${ROUTING_API_FQDN}`)
          middlewares:
            - name: routing-api-headers-middleware
#            - name: routing-api-ratelimit-middleware
            - name: routing-api-inflightreq-middleware
          services:
            - kind: Service
              name: routing-api
              port: 8082
