server:
  port: 8082
  shutdown: "graceful"
  servlet:
    context-path: /v1

springdoc:
  api-docs:
    path: /data-api
  swagger-ui:
    path: /api-docs.html

logging:
  level:
    org:
      springframework: INFO
      springframework.security: INFO
      springframework.web: INFO
      springframework.scheduling.concurrent: WARN
    root: INFO


spring:
  application:
    name: routing
  lifecycle:
    timeout-per-shutdown-phase: "10s"
  profiles:
    active: test
  data:
    rest:
      basePath: #/api
      detection-strategy: all

---

spring:
  profiles: test
security:
  disabled: true

---

spring:
  profiles: prod
security:
  disabled: false


---

gateway:
  service:
    dataapi:
      baseUrl: "http://localhost:8081/v1"
    adapter:
      path: "http://localhost:8084"
