server:
  port: 8090
  shutdown: "graceful"
  servlet:
    context-path: /

logging:
  level:
    org:
      springframework: ${LOG_LEVEL_SPRING:INFO}
      springframework.security: ${LOG_LEVEL_SPRING:INFO}
      springframework.web: ${LOG_LEVEL_SPRING:INFO}
      springframework.scheduling.concurrent: WARN
    root: ${LOG_LEVEL_SPRING:INFO}


spring:
  application:
    name: routing
  lifecycle:
    timeout-per-shutdown-phase: "30s"
  profiles:
    active: test
  data:
    rest:
      basePath: #/api
      detection-strategy: all
  redis:
    ssl: ${MAAS_API_CACHE_SSL:false}
    password: ${MAAS_API_CACHE_PASSWORD:}
    host: ${MAAS_API_CACHE_HOST:localhost}
    port: ${MAAS_API_CACHE_PORT:6379}
    connection-timeout: 30
    keys:
      prefix: ${MAAS_API_CACHE_KEYS_PREFIX:local}
    repositories:
      enabled: 'false'
  cache:
    type: redis

appli:
  use:
    cache: ${USE_CACHE:true}
---

spring:
  profiles: test
security:
  disabled: true

---

spring:
  profiles: prod
security:
  disabled: false


---

gateway:
  service:
    requestRelay:
      url: "http://${REQUEST_RELAY_FQDN:localhost}:8085/v1/request-relay"
      isMocked: false
    dataapi:
      baseUrl: "http://${DATA_API_FQDN:localhost}:8081/v1"
