server:
  port: 8080
  shutdown: "graceful"
  servlet:
    context-path: ${API_CONTEXT_PATH:/api/v1}
  error:
    whitelabel.enabled: false

springdoc:
  api-docs:
    path: /api
  swagger-ui:
    path: /api-docs.html

logging:
  level:
    org:
      springframework: ${LOG_LEVEL_SPRING:INFO}
      springframework.security: ${LOG_LEVEL_SPRING:INFO}
      springframework.web: ${LOG_LEVEL_SPRING:INFO}
      springframework.scheduling.concurrent: WARN
    root: ${LOG_LEVEL_SPRING:INFO}


spring:
  application:
    name: api
  lifecycle:
    timeout-per-shutdown-phase: "30s"
  profiles:
    active: test
  data:
    rest:
      basePath: #/api
      detection-strategy: all
  redis:
    ssl: ${MAAS_API_CACHE_SSL:false}
    password: ${MAAS_API_CACHE_PASSWORD:}
    host: ${MAAS_API_CACHE_HOST:localhost}
    port: ${MAAS_API_CACHE_PORT:6379}
    connection-timeout: 30
    keys:
      prefix: ${MAAS_API_CACHE_KEYS_PREFIX:local}
    repositories:
      enabled: 'false'
  cache:
    type: redis
  main:
    # To be removed if circular dependencies can be resolved in this project's services
    allow-circular-references: true

appli:
  use:
    cache: ${USE_CACHE:true}
---

spring:
  profiles: test
security:
  disabled: true

---

spring:
  profiles: prod
security:
  disabled: false

---

gateway:
  service:
    dataapi:
      baseUrl: "http://${DATA_API_HOST:localhost}:8081${DATA_API_CONTEXT_PATH:/dataapi/v1}"
    routingapi:
      baseurl: "http://${ROUTING_API_HOST:localhost}:8082/v1/route"
