sonarqube-verify-image-build:
  extends:
    - .image-job
  stage: prepare
  when: manual
  variables:
    MODULE_NAME: verify
    MODULE_PATH: delivery/commons/sonarqube
  except:
    variables:
      - $SKIP_TEST_N_VERIFY == "yes"
      - $CLEAN_DATA == "yes"
