version: '3'

services:
  custom-adapter:
     image: ${CUSTOM_ADAPTER_IMAGE_NAME}
     build:
       context: .
       dockerfile: ./custom-adapter-dockerfile.yml
       args:
         MAVEN_IMAGE_NAME: ${BASE_CUSTOM_ADAPTER_IMAGE_NAME}
     ports:
       - '8091'
     labels:
       - 'kompose.image-pull-secret=${GITLAB_IMAGE_PULL_SECRET_NAME}'
       - 'kompose.service.type=clusterip'
     environment:
       - SERVICE_BASE_PATH=${CUSTOM_ADAPTER_FQDN}
       - DATA_API_HOST=data-api.data-api-${CI_COMMIT_REF_SLUG}-${LANDSCAPE}.svc.cluster.local
       - REQUEST_RELAY_HOST=request-relay.request-relay-${CI_COMMIT_REF_SLUG}-${LANDSCAPE}.svc.cluster.local
       - MAAS_API_CACHE_HOST=redis.redis-${CI_COMMIT_REF_SLUG}-${LANDSCAPE}.svc.cluster.local
       - MAAS_API_CACHE_PORT=6379
       - MAAS_API_CACHE_KEYS_PREFIX=${MAAS_API_CACHE_KEYS_PREFIX}
       - MAAS_API_CACHE_PASSWORD=${MAAS_API_CACHE_PASSWORD}
       - DATA_API_CONTEXT_PATH=/dataapi/v1
 #    networks:
 #      - web-nw

# web network pour cloisonner une application
#networks:
#  web-nw: