{
 "title": "[MCM] [GW] Dashboard KPI Information Voyageur Covoiturage",
 "tags": [ "gateway" ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "partner_name",
    "label": "partner_name",
    "query": "select  name from msp.partner_meta order by name asc;"
   },
   {
    "name": "partner_id",
    "label": "partner_id",
    "query": "select partner_id from msp.partner_meta where name like  '$partner_name' ;"
   },
   {
    "name": "endpoints",
    "label": "Type recherche covoiturage",
    "query": "Trajets ponctuels conducteur : \"\\\\/partners\\\\/\\\\:partnerId\\\\/carpooling\\\\/driver_journeys\" , Trajets réguliers conducteur : \"\\\\/partners\\\\/\\\\:partnerId\\\\/carpooling\\\\/driver_regular_trips\" , Trajets ponctuels passager : \"\\\\/partners\\\\/\\\\:partnerId\\\\/carpooling\\\\/passenger_journeys\" , Trajets réguliers passager : \"\\\\/partners\\\\/\\\\:partnerId\\\\/carpooling\\\\/passenger_regular_trips\" , Tous trajets : \"\\\\/partners\\\\/\\\\:partnerId\\\\/carpooling\\\\/*\""
   },
   {
    "name": "operations",
    "query": "select path from flows where enabled=true and (path LIKE '/partners/:partnerId/carpooling/%_regular_trips' or path LIKE '/partners/:partnerId/carpooling/%_journeys') group by path "
   },
   {
    "name": "bookingType",
    "label": "Type de réservation",
    "query": "full api : \\\"MAAS\\\" , deeplink : \\\"MSP\\\" "
   }
  ]
 },
 "panels": [
  {
   "title": "Informations Voyageur Statiques",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 2, "w": 7, "x": 0, "y": 1 }, "options": { "content": "# Aujourd'hui" } },
    { "type": "text", "gridPos": { "h": 2, "w": 14, "x": 7, "y": 1 }, "options": { "content": "# Sur les 30 derniers jours" } },
    {
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
     "options": {
      "content": "<!-- driver_journeys  -->\n\n<h4 style=\"text-align: center\">Recherches de trajets ponctuels proposés par des conducteurs  (abouties ou en erreur)</h4>\n\n<div style=\"text-align:center; font-size: 45px\">\n<span style=\"color: rgb(115, 191, 105);font-weight:bold;\">{{count}}</span>\n</div>"
     },
     "targets": [
      {
       "body": "{\r\n \"query\": {\r\n    \"bool\": {\r\n      \"must\": [\r\n        {\r\n          \"query_string\": {\r\n            \"default_field\": \"path\",\r\n            \"query\": \"*\\\\/${partner_id}*\"\r\n          }\r\n        },\r\n        {\r\n          \"query_string\": {\r\n            \"query\": \"\\\\/partners\\\\/\\\\:partnerId\\\\/carpooling\\\\/driver_journeys\",\r\n            \"fields\": [\r\n              \"mapped-path\"\r\n            ]\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"now/d\",\r\n              \"lt\": \"now\"\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  }\r\n}",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "fields": [
        { "jsonPath": "$.count", "language": "jsonpath", "name": "count" }
       ],
       "headers": [
        [
         "Content-Type",
         "application/json"
        ]
       ],
       "method": "POST",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp",
       "urlPath": "/gravitee-request*/_count"
      }
     ]
    },
    {
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 3 },
     "options": {
      "content": "<!-- passenger_journeys  -->\n\n<h4 style=\"text-align: center\">Recherches de trajets ponctuels proposés par des passagers  (abouties ou en erreur)</h4>\n\n<div style=\"text-align:center; font-size: 45px\">\n<span style=\"color: rgb(115, 191, 105);font-weight:bold;\">{{count}}</span>\n</div>"
     },
     "targets": [
      {
       "body": "{\r\n \"query\": {\r\n    \"bool\": {\r\n      \"must\": [\r\n        {\r\n          \"query_string\": {\r\n            \"default_field\": \"path\",\r\n            \"query\": \"*\\\\/${partner_id}*\"\r\n          }\r\n        },{\r\n          \"query_string\": {\r\n            \"query\": \"\\\\/partners\\\\/\\\\:partnerId\\\\/carpooling\\\\/passenger_journeys\",\r\n            \"fields\": [\r\n              \"mapped-path\"\r\n            ]\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"now/d\",\r\n              \"lt\": \"now\"\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  }\r\n}",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "fields": [
        { "jsonPath": "$.count", "language": "jsonpath", "name": "" }
       ],
       "headers": [
        [
         "Content-Type",
         "application/json"
        ]
       ],
       "method": "POST",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp",
       "urlPath": "/gravitee-request*/_count"
      }
     ]
    },
    {
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 6, "w": 14, "x": 7, "y": 3 },
     "options": {
      "content": "<h3>Sommes :</h3>\n\n- Recherches de trajets ponctuels proposés par des conducteurs :  <span style=\"color: green;font-weight:bold;font-size: 16px\">{{count_driver_journeys}}</span> recherches (abouties ou en erreur) sur 30 jours\n\n- Recherches de trajets réguliers proposés par des conducteurs :  <span style=\"color: green;font-weight:bold;font-size: 16px\">{{count_driver_regular_trips}}</span> recherches (abouties ou en erreur) sur 30 jours\n\n- Recherches de trajets ponctuels proposés par des passagers:   <span style=\"color: green;font-weight:bold;font-size: 16px\">{{count_passenger_journeys}}</span> recherches (abouties ou en erreur) sur 30 jours\n- Recherches de trajets réguliers proposés par des passagers:   <span style=\"color: green;font-weight:bold;font-size: 16px\">{{count_passenger_regular_trips}}</span> recherches (abouties ou en erreur) sur 30 jours"
     },
     "targets": [
      {
       "body": "{ \r\n  \"aggs\": {\r\n    \"endpoints\": {\r\n      \"terms\": {\r\n        \"field\": \"mapped-path\",\r\n        \"min_doc_count\": 0, \r\n        \"include\": \"partnerId.*|.*\\\\carpooling.*|.*\\\\passenger.*\",\r\n        \"exclude\": \"partnerId.*|.*\\\\booking.*|.*\\\\booking.*\",\r\n        \"order\": {\r\n          \"_count\": \"desc\"\r\n        },\r\n        \"size\": 5\r\n      }\r\n    }\r\n  },\r\n  \"size\": 0,\r\n  \"script_fields\": {},\r\n  \"stored_fields\": [\r\n    \"*\"\r\n  ],\r\n  \"runtime_mappings\": {},\r\n  \"query\": {\r\n    \"bool\": {\r\n      \"must\": [\r\n        {\r\n          \"query_string\":{\r\n            \"default_field\":\"path\",\r\n            \"query\":\"*\\\\/${partner_id}*\"\r\n          }\r\n        }\r\n      ],\r\n      \"filter\": [\r\n        {\r\n          \"bool\": {\r\n            \"should\": [\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"mapped-path\": \"/partners/:partnerId/carpooling/driver_journeys\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              },\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"mapped-path\": \"/partners/:partnerId/carpooling/passenger_journeys\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              },\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"mapped-path\": \"/partners/:partnerId/carpooling/driver_regular_trips\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              },\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"mapped-path\": \"/partners/:partnerId/carpooling/passenger_regular_trips\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              }\r\n            ],\r\n            \"minimum_should_match\": 1\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"now-30d\",\r\n              \"lt\": \"now\"\r\n            }\r\n          }\r\n        }\r\n      ],\r\n      \"should\": [],\r\n      \"must_not\": []\r\n    }\r\n  }\r\n}",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "fields": [
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key==\"/partners/:partnerId/carpooling/driver_journeys\")].doc_count",
         "language": "jsonpath",
         "name": "count_driver_journeys"
        },
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key==\"/partners/:partnerId/carpooling/driver_regular_trips\")].doc_count",
         "language": "jsonpath",
         "name": "count_driver_regular_trips"
        },
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key==\"/partners/:partnerId/carpooling/passenger_journeys\")].doc_count",
         "language": "jsonpath",
         "name": "count_passenger_journeys"
        },
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key==\"/partners/:partnerId/carpooling/passenger_regular_trips\")].doc_count",
         "language": "jsonpath",
         "name": "count_passenger_regular_trips"
        }
       ],
       "headers": [
        [
         "Content-Type",
         "application/json"
        ]
       ],
       "method": "POST",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp",
       "urlPath": "/gravitee-request*/_search"
      }
     ]
    },
    {
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
     "options": {
      "content": "<!-- driver_regular_trips  -->\n\n<h4 style=\"text-align: center\">Recherches de trajets réguliers proposés par des conducteurs  (abouties ou en erreur)</h4>\n\n<div style=\"text-align:center; font-size: 45px\">\n<span style=\"color: rgb(115, 191, 105);font-weight:bold;\">{{count}}</span>\n</div>"
     },
     "targets": [
      {
       "body": "{\r\n \"query\": {\r\n    \"bool\": {\r\n      \"must\": [\r\n        {\r\n          \"query_string\": {\r\n            \"default_field\": \"path\",\r\n            \"query\": \"*\\\\/${partner_id}*\"\r\n          }\r\n        },{\r\n          \"query_string\": {\r\n            \"query\": \"\\\\/partners\\\\/\\\\:partnerId\\\\/carpooling\\\\/driver_regular_trips\",\r\n            \"fields\": [\r\n              \"mapped-path\"\r\n            ]\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"now/d\",\r\n              \"lt\": \"now\"\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  }\r\n}",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "fields": [
        { "jsonPath": "$.count", "language": "jsonpath", "name": "" }
       ],
       "headers": [
        [
         "Content-Type",
         "application/json"
        ]
       ],
       "method": "POST",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp",
       "urlPath": "/gravitee-request*/_count"
      }
     ]
    },
    {
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
     "options": {
      "content": "<!-- passenger_regular_trips  -->\n\n<h4 style=\"text-align: center\">Recherches de trajets réguliers proposés par des passagers  (abouties ou en erreur) </h4>\n\n<div style=\"text-align:center; font-size: 45px\">\n<span style=\"color: rgb(115, 191, 105);font-weight:bold;\">{{count}}</span>\n</div>"
     },
     "targets": [
      {
       "body": "{\r\n \"query\": {\r\n    \"bool\": {\r\n      \"must\": [\r\n        {\r\n          \"query_string\": {\r\n            \"default_field\": \"path\",\r\n            \"query\": \"*\\\\/${partner_id}*\"\r\n          }\r\n        },{\r\n          \"query_string\": {\r\n            \"query\": \"\\\\/partners\\\\/\\\\:partnerId\\\\/carpooling\\\\/passenger_regular_trips\",\r\n            \"fields\": [\r\n              \"mapped-path\"\r\n            ]\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"now/d\",\r\n              \"lt\": \"now\"\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  }\r\n}",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "fields": [
        { "jsonPath": "$.count", "language": "jsonpath", "name": "" }
       ],
       "headers": [
        [
         "Content-Type",
         "application/json"
        ]
       ],
       "method": "POST",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp",
       "urlPath": "/gravitee-request*/_count"
      }
     ]
    },
    {
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 6, "w": 14, "x": 7, "y": 9 },
     "options": {
      "content": "<h3>Moyennes journalières : </h3>\n\n- Recherches de trajets ponctuels proposés par des conducteurs :  <span style=\"color: green;font-weight:bold;font-size: 16px\">{{toFixed count_driver_journeys 2}}</span> recherches  (abouties ou en erreur) / jour\n\n- Recherches de trajets réguliers proposés par des conducteurs :  <span style=\"color: green;font-weight:bold;font-size: 16px\">{{toFixed count_driver_regular_trips 2}}</span> recherches  (abouties ou en erreur) / jour\n\n- Recherches de trajets ponctuels proposés par des passagers:   <span style=\"color: green;font-weight:bold;font-size: 16px\">{{toFixed count_passenger_journeys 2}}</span> recherches  (abouties ou en erreur) / jour\n- Recherches de trajets réguliers proposés par des passagers:   <span style=\"color: green;font-weight:bold;font-size: 16px\">{{toFixed count_passenger_regular_trips 2}}</span> recherches  (abouties ou en erreur) / jour"
     },
     "targets": [
      {
       "body": "{\r\n  \"aggs\": {\r\n    \"endpoints\": {\r\n      \"terms\": {\r\n        \"field\": \"mapped-path\",\r\n        \"min_doc_count\": 0, \r\n        \"include\": \"partnerId.*|.*\\\\carpooling.*|.*\\\\passenger.*\",\r\n        \"exclude\": \"partnerId.*|.*\\\\booking.*|.*\\\\booking.*\",\r\n        \"order\": {\r\n          \"_key\": \"desc\"\r\n        },\r\n        \"size\": 8\r\n      },\r\n      \"aggs\": {\r\n        \"histo-by-endpoint\": {\r\n          \"sum_bucket\": {\r\n            \"buckets_path\": \"histo-by-endpoint-bucket>_count\",\r\n            \"gap_policy\": \"insert_zeros\"\r\n          }\r\n        },\r\n        \"moyenne\": {\r\n          \"bucket_script\": {\r\n            \"buckets_path\": {\r\n              \"somme_mensuelle\": \"histo-by-endpoint\"\r\n            },\r\n            \"script\": \"params.somme_mensuelle/30\",\r\n            \"gap_policy\": \"insert_zeros\"\r\n          }\r\n        },\r\n        \"histo-by-endpoint-bucket\": {\r\n          \"date_histogram\": {\r\n            \"field\": \"@timestamp\",\r\n            \"calendar_interval\": \"1d\",\r\n            \"time_zone\": \"Europe/Paris\",\r\n            \"min_doc_count\": 1\r\n          }\r\n        }\r\n      }\r\n    }\r\n  },\r\n  \"size\": 0,\r\n  \"script_fields\": {},\r\n  \"stored_fields\": [\r\n    \"*\"\r\n  ],\r\n  \"runtime_mappings\": {},\r\n  \"query\": {\r\n    \"bool\": {\r\n      \"must\": [\r\n        {\r\n          \"query_string\":{\r\n            \"default_field\":\"path\",\r\n            \"query\":\"*\\\\/${partner_id}*\"\r\n          }\r\n        }\r\n      ],\r\n      \"filter\": [\r\n        {\r\n          \"bool\": {\r\n            \"should\": [\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"mapped-path\": \"/partners/:partnerId/carpooling/driver_journeys\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              },\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"mapped-path\": \"/partners/:partnerId/carpooling/passenger_journeys\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              },\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"mapped-path\": \"/partners/:partnerId/carpooling/driver_regular_trips\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              },\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"mapped-path\": \"/partners/:partnerId/carpooling/passenger_regular_trips\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              }\r\n            ],\r\n            \"minimum_should_match\": 1\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"now-30d\",\r\n              \"lt\": \"now\"\r\n            }\r\n          }\r\n        }\r\n      ],\r\n      \"should\": [],\r\n      \"must_not\": []\r\n    }\r\n  }\r\n}",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "fields": [
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key==\"/partners/:partnerId/carpooling/driver_journeys\")].moyenne.value",
         "language": "jsonpath",
         "name": "count_driver_journeys"
        },
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key==\"/partners/:partnerId/carpooling/driver_regular_trips\")].moyenne.value",
         "language": "jsonpath",
         "name": "count_driver_regular_trips"
        },
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key==\"/partners/:partnerId/carpooling/passenger_journeys\")].moyenne.value",
         "language": "jsonpath",
         "name": "count_passenger_journeys"
        },
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key==\"/partners/:partnerId/carpooling/passenger_regular_trips\")].moyenne.value",
         "language": "jsonpath",
         "name": "count_passenger_regular_trips"
        }
       ],
       "headers": [
        [
         "Content-Type",
         "application/json"
        ]
       ],
       "method": "POST",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp",
       "urlPath": "/gravitee-request*/_search"
      }
     ]
    },
    {
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 5, "w": 3, "x": 2, "y": 13 },
     "options": {
      "content": "<!-- passenger_regular_trips  -->\n\n<h4 style=\"text-align: center\"> Total de recherches de trajets  (abouties ou en erreur)</h4>\n\n<div style=\"text-align:center; font-size: 45px\">\n<span style=\"color: rgb(115, 191, 105);font-weight:bold;\">{{count}}</span>\n</div>"
     },
     "targets": [
      {
       "body": "{\r\n \"query\": {\r\n    \"bool\": {\r\n      \"must\": [\r\n        {\r\n          \"query_string\": {\r\n            \"default_field\": \"path\",\r\n            \"query\": \"*\\\\/${partner_id}*\"\r\n          }\r\n        },{\r\n          \"query_string\": {\r\n            \"query\": \"\\\\/partners\\\\/\\\\:partnerId\\\\/carpooling\\\\/*\",\r\n            \"fields\": [\r\n              \"mapped-path\"\r\n            ]\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"now/d\",\r\n              \"lt\": \"now\"\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  }\r\n}",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "fields": [
        { "jsonPath": "$.count", "language": "jsonpath", "name": "" }
       ],
       "headers": [
        [
         "Content-Type",
         "application/json"
        ]
       ],
       "method": "POST",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp",
       "urlPath": "/gravitee-request*/_count"
      }
     ]
    },
    {
     "title": "Recherche de trajets   (abouties ou en erreur) sur les 30 derniers jours",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 14, "x": 7, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "body": "{\r\n  \"aggs\": {\r\n    \"endpoints\": {\r\n      \"terms\": {\r\n        \"field\": \"mapped-path\",\r\n        \"min_doc_count\": 0,\r\n        \"include\": \"partnerId.*|.*\\\\carpooling.*|.*\\\\passenger.*\",\r\n        \"exclude\": \"partnerId.*|.*\\\\booking.*|.*\\\\booking.*\",\r\n        \"order\": {\r\n          \"_key\": \"desc\"\r\n        },\r\n        \"size\": 8\r\n      },\r\n      \"aggs\": {\r\n        \"histo-by-endpoint-bucket\": {\r\n          \"date_histogram\": {\r\n            \"field\": \"@timestamp\",\r\n            \"calendar_interval\": \"1d\",\r\n            \"time_zone\": \"Europe/Paris\",\r\n            \"min_doc_count\": 0,\r\n            \"extended_bounds\": {\r\n              \"min\": \"now-30d\",\r\n              \"max\": \"now\"\r\n            },\r\n            \"order\": {\r\n              \"_key\": \"asc\"\r\n            }\r\n          }\r\n        }\r\n      }\r\n    }\r\n  },\r\n  \"size\": 0,\r\n  \"script_fields\": {},\r\n  \"stored_fields\": [\r\n    \"*\"\r\n  ],\r\n  \"runtime_mappings\": {},\r\n  \"query\": {\r\n    \"bool\": {\r\n      \"must\": [\r\n        {\r\n          \"query_string\":{\r\n            \"default_field\":\"path\",\r\n            \"query\":\"*\\\\/${partner_id}*\"\r\n          }\r\n        }\r\n      ],\r\n      \"filter\": [\r\n        {\r\n          \"bool\": {\r\n            \"should\": [\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"mapped-path\": \"/partners/:partnerId/carpooling/driver_journeys\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              },\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"mapped-path\": \"/partners/:partnerId/carpooling/passenger_journeys\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              },\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"mapped-path\": \"/partners/:partnerId/carpooling/driver_regular_trips\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              },\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"mapped-path\": \"/partners/:partnerId/carpooling/passenger_regular_trips\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              }\r\n            ],\r\n            \"minimum_should_match\": 1\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"now-30d\",\r\n              \"lt\": \"now\"\r\n            }\r\n          }\r\n        }\r\n      ],\r\n      \"should\": [],\r\n      \"must_not\": []\r\n    }\r\n  }\r\n}",
       "fields": [
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key == \"/partners/:partnerId/carpooling/driver_journeys\")].histo-by-endpoint-bucket.buckets[*].key",
         "language": "jsonpath",
         "name": "jour",
         "type": "time"
        },
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key == \"/partners/:partnerId/carpooling/driver_journeys\")].histo-by-endpoint-bucket.buckets[*].doc_count",
         "language": "jsonpath",
         "name": "Trajets ponctuels proposés par les conducteurs "
        },
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key == \"/partners/:partnerId/carpooling/passenger_journeys\")].histo-by-endpoint-bucket.buckets[*].doc_count",
         "language": "jsonpath",
         "name": "Trajets ponctuels demandés  par les passagers"
        },
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key == \"/partners/:partnerId/carpooling/driver_regular_trips\")].histo-by-endpoint-bucket.buckets[*].doc_count",
         "language": "jsonpath",
         "name": "Trajets réguliers proposés par les conducteurs "
        },
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key == \"/partners/:partnerId/carpooling/passenger_regular_trips\")].histo-by-endpoint-bucket.buckets[*].doc_count",
         "language": "jsonpath",
         "name": "Trajets réguliers demandés  par les passagers"
        }
       ],
       "method": "POST",
       "urlPath": "/gravitee-request-*/_search?size=0"
      }
     ]
    }
   ]
  },
  {
   "title": "Nombre de recherches abouties en fonction du nombre de résultats retournés (sur les derniers 30 jours)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pour trajets ponctuels proposés par des conducteurs ",
     "type": "bargauge",
     "description": "Par palier de nombre de trajets retournés, ce graphe présente le nombre de recherches de trajets ponctuels proposés par les conducteurs.",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "body": "{\r\n  \"size\": 0,\r\n  \"aggs\": {\r\n    \"response-size\": {\r\n      \"range\": {\r\n        \"field\": \"client-response.headers.X-RESPONSE-SIZE\",\r\n        \"ranges\": [\r\n         {\r\n            \"key\": \"totalNonNull\",\r\n            \"from\": 1\r\n          },\r\n          {\r\n            \"key\": \"Null\",\r\n            \"from\": 0,\r\n            \"to\": 1\r\n          },\r\n          {\r\n            \"key\": \"faible\",\r\n            \"from\": 1,\r\n            \"to\": 6\r\n          },\r\n          {\r\n            \"key\": \"moyen\",\r\n            \"from\": 6,\r\n            \"to\": 11\r\n          },\r\n          {\r\n            \"key\": \"Haut\",\r\n            \"from\": 11\r\n          }\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  \"runtime_mappings\": {\r\n    \"client-response.headers.X-MAPPED-PATH\": {\r\n      \"type\": \"keyword\"\r\n    },\r\n    \"client-response.headers.X-RESPONSE-SIZE\": {\r\n      \"type\": \"long\"\r\n    }\r\n  },\r\n    \"query\": {\r\n    \"bool\": {\r\n      \"filter\": [\r\n        {\r\n          \"range\": {\r\n            \"client-response.status\": {\r\n              \"lt\": 299,\r\n              \"gte\": 200\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"bool\": {\r\n            \"should\": [\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"client-response.headers.X-MAPPED-PATH\": \"/partners/:partnerId/carpooling/driver_journeys\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              }\r\n            ],\r\n            \"minimum_should_match\": 1\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"now-30d\",\r\n              \"lt\": \"now\"\r\n            }\r\n          }\r\n        }\r\n      ],\r\n      \"should\": [],\r\n      \"must_not\": []\r\n    }\r\n  }\r\n}",
       "fields": [
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"Null\")].doc_count",
         "name": "0 trajet"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"faible\")].doc_count",
         "language": "jsonpath",
         "name": "Entre 1 et 5 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"moyen\")].doc_count",
         "language": "jsonpath",
         "name": "Entre 6 et 10 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"Haut\")].doc_count",
         "language": "jsonpath",
         "name": "Supérieur à 10 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"totalNonNull\")].doc_count",
         "language": "jsonpath",
         "name": "Total recherches avec au moins 1 trajet"
        }
       ],
       "method": "POST",
       "urlPath": "/gravitee-log*/_search?timeout=9000s"
      }
     ]
    },
    {
     "title": "Pour trajets ponctuels demandés par des passagers",
     "type": "bargauge",
     "description": "Par palier de nombre de trajets retournés, ce graphe présente le nombre de recherches de trajets ponctuels demandés par les passagers.",
     "gridPos": { "h": 9, "w": 12, "x": 11, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "body": "{\r\n  \"size\": 0,\r\n  \"aggs\": {\r\n    \"response-size\": {\r\n      \"range\": {\r\n        \"field\": \"client-response.headers.X-RESPONSE-SIZE\",\r\n        \"ranges\": [\r\n          {\r\n            \"key\": \"totalNonNull\",\r\n            \"from\": 1\r\n          },\r\n          {\r\n            \"key\": \"Null\",\r\n            \"from\": 0,\r\n            \"to\": 1\r\n          },\r\n          {\r\n            \"key\": \"faible\",\r\n            \"from\": 1,\r\n            \"to\": 6\r\n          },\r\n          {\r\n            \"key\": \"moyen\",\r\n            \"from\": 6,\r\n            \"to\": 11\r\n          },\r\n          {\r\n            \"key\": \"Haut\",\r\n            \"from\": 11\r\n          }\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  \"runtime_mappings\": {\r\n    \"client-response.headers.X-MAPPED-PATH\": {\r\n      \"type\": \"keyword\"\r\n    },\r\n    \"client-response.headers.X-RESPONSE-SIZE\": {\r\n      \"type\": \"long\"\r\n    }\r\n  },\r\n    \"query\": {\r\n    \"bool\": {\r\n      \"filter\": [\r\n        {\r\n          \"range\": {\r\n            \"client-response.status\": {\r\n              \"lt\": 299,\r\n              \"gte\": 200\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"bool\": {\r\n            \"should\": [\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"client-response.headers.X-MAPPED-PATH\": \"/partners/:partnerId/carpooling/passenger_journeys\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              }\r\n            ],\r\n            \"minimum_should_match\": 1\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"now-30d\",\r\n              \"lt\": \"now\"\r\n            }\r\n          }\r\n        }\r\n      ],\r\n      \"should\": [],\r\n      \"must_not\": []\r\n    }\r\n  }\r\n}",
       "fields": [
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"Null\")].doc_count",
         "name": "0 trajet"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"faible\")].doc_count",
         "language": "jsonpath",
         "name": "Entre 1 et 5 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"moyen\")].doc_count",
         "language": "jsonpath",
         "name": "Entre 6 et 10 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"Haut\")].doc_count",
         "language": "jsonpath",
         "name": "Supérieur à 10 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"totalNonNull\")].doc_count",
         "language": "jsonpath",
         "name": "Total recherches avec au moins 1 trajet"
        }
       ],
       "method": "POST",
       "urlPath": "/gravitee-log*/_search?timeout=9000s"
      }
     ]
    },
    {
     "title": "Pour trajets réguliers proposés par des conducteurs",
     "type": "bargauge",
     "description": "Par palier de nombre de trajets retournés, ce graphe présente le nombre de recherches de trajets réguliers proposés par les conducteurs.",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "body": "{\r\n  \"size\": 0,\r\n  \"aggs\": {\r\n    \"response-size\": {\r\n      \"range\": {\r\n        \"field\": \"client-response.headers.X-RESPONSE-SIZE\",\r\n        \"ranges\": [\r\n           {\r\n            \"key\": \"totalNonNull\",\r\n            \"from\": 1\r\n          },\r\n          {\r\n            \"key\": \"Null\",\r\n            \"from\": 0,\r\n            \"to\": 1\r\n          },\r\n          {\r\n            \"key\": \"faible\",\r\n            \"from\": 1,\r\n            \"to\": 6\r\n          },\r\n          {\r\n            \"key\": \"moyen\",\r\n            \"from\": 6,\r\n            \"to\": 11\r\n          },\r\n          {\r\n            \"key\": \"Haut\",\r\n            \"from\": 11\r\n          }\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  \"runtime_mappings\": {\r\n    \"client-response.headers.X-MAPPED-PATH\": {\r\n      \"type\": \"keyword\"\r\n    },\r\n    \"client-response.headers.X-RESPONSE-SIZE\": {\r\n      \"type\": \"long\"\r\n    }\r\n  },\r\n    \"query\": {\r\n    \"bool\": {\r\n      \"filter\": [\r\n        {\r\n          \"range\": {\r\n            \"client-response.status\": {\r\n              \"lt\": 299,\r\n              \"gte\": 200\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"bool\": {\r\n            \"should\": [\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"client-response.headers.X-MAPPED-PATH\": \"/partners/:partnerId/carpooling/driver_regular_trips\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              }\r\n            ],\r\n            \"minimum_should_match\": 1\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"now-30d\",\r\n              \"lt\": \"now\"\r\n            }\r\n          }\r\n        }\r\n      ],\r\n      \"should\": [],\r\n      \"must_not\": []\r\n    }\r\n  }\r\n}",
       "fields": [
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"Null\")].doc_count",
         "name": "0 trajet"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"faible\")].doc_count",
         "language": "jsonpath",
         "name": "Entre 1 et 5 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"moyen\")].doc_count",
         "language": "jsonpath",
         "name": "Entre 6 et 10 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"Haut\")].doc_count",
         "language": "jsonpath",
         "name": "Supérieur à 10 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"totalNonNull\")].doc_count",
         "language": "jsonpath",
         "name": "Total recherches avec au moins 1 trajet"
        }
       ],
       "method": "POST",
       "urlPath": "/gravitee-log*/_search?timeout=9000s"
      }
     ]
    },
    {
     "title": "Pour trajets réguliers demandés par des passagers",
     "type": "bargauge",
     "description": "Par palier de nombre de trajets retournés, ce graphe présente le nombre de recherches de trajets réguliers demandés par les passagers.",
     "gridPos": { "h": 9, "w": 12, "x": 11, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "body": "{\r\n  \"size\": 0,\r\n  \"aggs\": {\r\n    \"response-size\": {\r\n      \"range\": {\r\n        \"field\": \"client-response.headers.X-RESPONSE-SIZE\",\r\n        \"ranges\": [\r\n          {\r\n            \"key\": \"totalNonNull\",\r\n            \"from\": 1\r\n          },\r\n          {\r\n            \"key\": \"Null\",\r\n            \"from\": 0,\r\n            \"to\": 1\r\n          },\r\n          {\r\n            \"key\": \"faible\",\r\n            \"from\": 1,\r\n            \"to\": 6\r\n          },\r\n          {\r\n            \"key\": \"moyen\",\r\n            \"from\": 6,\r\n            \"to\": 11\r\n          },\r\n          {\r\n            \"key\": \"Haut\",\r\n            \"from\": 11\r\n          }\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  \"runtime_mappings\": {\r\n    \"client-response.headers.X-MAPPED-PATH\": {\r\n      \"type\": \"keyword\"\r\n    },\r\n    \"client-response.headers.X-RESPONSE-SIZE\": {\r\n      \"type\": \"long\"\r\n    }\r\n  },\r\n    \"query\": {\r\n    \"bool\": {\r\n      \"filter\": [\r\n        {\r\n          \"range\": {\r\n            \"client-response.status\": {\r\n              \"lt\": 299,\r\n              \"gte\": 200\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"bool\": {\r\n            \"should\": [\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"client-response.headers.X-MAPPED-PATH\": \"/partners/:partnerId/carpooling/passenger_regular_trips\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              }\r\n            ],\r\n            \"minimum_should_match\": 1\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"now-30d\",\r\n              \"lt\": \"now\"\r\n            }\r\n          }\r\n        }\r\n      ],\r\n      \"should\": [],\r\n      \"must_not\": []\r\n    }\r\n  }\r\n}",
       "fields": [
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"Null\")].doc_count",
         "name": "0 trajet"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"faible\")].doc_count",
         "language": "jsonpath",
         "name": "Entre 1 et 5 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"moyen\")].doc_count",
         "language": "jsonpath",
         "name": "Entre 6 et 10 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"Haut\")].doc_count",
         "language": "jsonpath",
         "name": "Supérieur à 10 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"totalNonNull\")].doc_count",
         "language": "jsonpath",
         "name": "Total recherches avec au moins 1 trajet"
        }
       ],
       "method": "POST",
       "urlPath": "/gravitee-log*/_search?timeout=9000s"
      }
     ]
    }
   ]
  },
  {
   "title": "Informations Voyageur Dynamiques",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Recherches de $endpoints  (abouties ou en erreur)",
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
     "repeat": "endpoints",
     "options": {
      "content": "<div style=\"text-align:center; font-size: 45px\">\n<span style=\"color: rgb(115, 191, 105);font-weight:bold;\">{{count}}</span>\n</div>"
     },
     "targets": [
      {
       "body": "{\r\n  \"query\": {\r\n    \"bool\": {\r\n      \"must\": [\r\n        {\r\n          \"query_string\":{\r\n            \"default_field\":\"path\",\r\n            \"query\":\"*\\\\/${partner_id}*\"\r\n          }\r\n        }\r\n      ],\r\n      \"filter\": [\r\n        {\r\n          \"bool\": {\r\n            \"filter\": [\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"bool\": {\r\n                        \"should\": [\r\n                          {\r\n                            \"match_phrase\": {\r\n                              \"mapped-path\": \"/partners/:partnerId/carpooling/driver_journeys\"\r\n                            }\r\n                          }\r\n                        ]\r\n                      }\r\n                    },\r\n                    {\r\n                      \"bool\": {\r\n                        \"should\": [\r\n                          {\r\n                            \"match_phrase\": {\r\n                              \"mapped-path\": \"/partners/:partnerId/carpooling/passenger_journeys\"\r\n                            }\r\n                          }\r\n                        ]\r\n                      }\r\n                    },\r\n                    {\r\n                      \"bool\": {\r\n                        \"should\": [\r\n                          {\r\n                            \"match_phrase\": {\r\n                              \"mapped-path\": \"/partners/:partnerId/carpooling/driver_regular_trips\"\r\n                            }\r\n                          }\r\n                        ]\r\n                      }\r\n                    },\r\n                    {\r\n                      \"bool\": {\r\n                        \"should\": [\r\n                          {\r\n                            \"match_phrase\": {\r\n                              \"mapped-path\": \"/partners/:partnerId/carpooling/passenger_regular_trips\"\r\n                            }\r\n                          }\r\n                        ]\r\n                      }\r\n                    }\r\n                  ]\r\n                }\r\n              },\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"query_string\": {\r\n                        \"query\": $endpoints,\r\n                        \"fields\": [\r\n                          \"mapped-path\"\r\n                        ]\r\n                      }\r\n                    }\r\n                  ]\r\n                }\r\n              }\r\n            ]\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"${__from:date:iso}\",\r\n              \"lt\": \"${__to:date:iso}\"\r\n            }\r\n          }\r\n        }\r\n      ],\r\n      \"should\": [],\r\n      \"must_not\": []\r\n    }\r\n  }\r\n}",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "fields": [
        { "jsonPath": "$.count", "language": "jsonpath", "name": "" }
       ],
       "headers": [
        [
         "Content-Type",
         "application/json"
        ]
       ],
       "method": "POST",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp",
       "urlPath": "/gravitee-request*/_count"
      }
     ]
    },
    {
     "title": "Recherche  dynamique de trajets  (abouties ou en erreur)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "body": "{\r\n  \"aggs\": {\r\n    \"endpoints\": {\r\n      \"terms\": {\r\n        \"field\": \"mapped-path\",\r\n        \"min_doc_count\": 0, \r\n       \"include\": \"partnerId.*|.*\\\\carpooling.*|.*\\\\passenger.*\",\r\n        \"exclude\": \"partnerId.*|.*\\\\booking.*|.*\\\\booking.*\",\r\n        \"order\": {\r\n          \"_key\": \"desc\"\r\n        },\r\n        \"size\": 8\r\n      },\r\n      \"aggs\": {\r\n        \"histo-by-endpoint-bucket\": {\r\n          \"date_histogram\": {\r\n            \"field\": \"@timestamp\",\r\n            \"calendar_interval\": \"1d\",\r\n            \"time_zone\": \"Europe/Paris\",\r\n            \"min_doc_count\": 0,\r\n            \"extended_bounds\": {\r\n              \"min\": \"${__from:date:iso}\",\r\n              \"max\": \"${__to:date:iso}\"\r\n            },\r\n            \"order\": {\r\n              \"_key\": \"asc\"\r\n            }\r\n          }\r\n        }\r\n      }\r\n    }\r\n  },\r\n  \"size\": 0,\r\n  \"script_fields\": {},\r\n  \"stored_fields\": [\r\n    \"*\"\r\n  ],\r\n  \"runtime_mappings\": {},\r\n  \"query\": {\r\n    \"bool\": {\r\n      \"must\": [\r\n        {\r\n          \"query_string\":{\r\n            \"default_field\":\"path\",\r\n            \"query\":\"*\\\\/${partner_id}*\"\r\n          }\r\n        }\r\n      ],\r\n      \"filter\": [\r\n        {\r\n          \"bool\": {\r\n            \"should\": [\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"mapped-path\": \"/partners/:partnerId/carpooling/driver_journeys\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              },\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"mapped-path\": \"/partners/:partnerId/carpooling/passenger_journeys\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              },\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"mapped-path\": \"/partners/:partnerId/carpooling/driver_regular_trips\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              },\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"mapped-path\": \"/partners/:partnerId/carpooling/passenger_regular_trips\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              }\r\n            ],\r\n            \"minimum_should_match\": 1\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"${__from:date:iso}\",\r\n              \"lt\": \"${__to:date:iso}\"\r\n            }\r\n          }\r\n        }\r\n      ],\r\n      \"should\": [],\r\n      \"must_not\": []\r\n    }\r\n  }\r\n}",
       "fields": [
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key == \"/partners/:partnerId/carpooling/driver_journeys\")].histo-by-endpoint-bucket.buckets[*].key",
         "language": "jsonpath",
         "name": "jour",
         "type": "time"
        },
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key == \"/partners/:partnerId/carpooling/driver_journeys\")].histo-by-endpoint-bucket.buckets[*].doc_count",
         "language": "jsonpath",
         "name": "Trajets ponctuels proposés par les conducteurs "
        },
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key == \"/partners/:partnerId/carpooling/passenger_journeys\")].histo-by-endpoint-bucket.buckets[*].doc_count",
         "language": "jsonpath",
         "name": "Trajets ponctuels demandés  par les passagers"
        },
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key == \"/partners/:partnerId/carpooling/driver_regular_trips\")].histo-by-endpoint-bucket.buckets[*].doc_count",
         "language": "jsonpath",
         "name": "Trajets réguliers proposés par les conducteurs "
        },
        {
         "jsonPath": "$.aggregations.endpoints.buckets[?(@.key == \"/partners/:partnerId/carpooling/passenger_regular_trips\")].histo-by-endpoint-bucket.buckets[*].doc_count",
         "language": "jsonpath",
         "name": "Trajets réguliers demandés  par les passagers"
        }
       ],
       "method": "POST",
       "urlPath": "/gravitee-request-*/_search?size=0"
      }
     ]
    }
   ]
  },
  {
   "title": "Nombre de recherches abouties en fonction du nombre de résultats retournés (partie dynamique)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pour trajets ponctuels proposés par des conducteurs",
     "type": "bargauge",
     "description": "Par palier de nombre de trajets retournés, ce graphe présente le nombre de recherches de trajets ponctuels proposés par les conducteurs.",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "body": "{\r\n  \"size\": 0,\r\n  \"aggs\": {\r\n    \"response-size\": {\r\n      \"range\": {\r\n        \"field\": \"client-response.headers.X-RESPONSE-SIZE\",\r\n        \"ranges\": [\r\n         {\r\n            \"key\": \"totalNonNull\",\r\n            \"from\": 1\r\n          },\r\n          {\r\n            \"key\": \"Null\",\r\n            \"from\": 0,\r\n            \"to\": 1\r\n          },\r\n          {\r\n            \"key\": \"faible\",\r\n            \"from\": 1,\r\n            \"to\": 6\r\n          },\r\n          {\r\n            \"key\": \"moyen\",\r\n            \"from\": 6,\r\n            \"to\": 11\r\n          },\r\n          {\r\n            \"key\": \"Haut\",\r\n            \"from\": 11\r\n          }\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  \"runtime_mappings\": {\r\n    \"client-response.headers.X-MAPPED-PATH\": {\r\n      \"type\": \"keyword\"\r\n    },\r\n    \"client-response.headers.X-RESPONSE-SIZE\": {\r\n      \"type\": \"long\"\r\n    }\r\n  },\r\n    \"query\": {\r\n    \"bool\": {\r\n      \"filter\": [\r\n        {\r\n          \"range\": {\r\n            \"client-response.status\": {\r\n              \"lt\": 299,\r\n              \"gte\": 200\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"bool\": {\r\n            \"should\": [\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"client-response.headers.X-MAPPED-PATH\": \"/partners/:partnerId/carpooling/driver_journeys\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              }\r\n            ],\r\n            \"minimum_should_match\": 1\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n               \"gte\": \"${__from:date:iso}\",\r\n              \"lt\": \"${__to:date:iso}\"\r\n            }\r\n          }\r\n        }\r\n      ],\r\n      \"should\": [],\r\n      \"must_not\": []\r\n    }\r\n  }\r\n}",
       "fields": [
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"Null\")].doc_count",
         "name": "0 trajet"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"faible\")].doc_count",
         "language": "jsonpath",
         "name": "Entre 1 et 5 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"moyen\")].doc_count",
         "language": "jsonpath",
         "name": "Entre 6 et 10 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"Haut\")].doc_count",
         "language": "jsonpath",
         "name": "Supérieur à 10 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"totalNonNull\")].doc_count",
         "language": "jsonpath",
         "name": "Total recherches avec au moins 1 trajet"
        }
       ],
       "method": "POST",
       "urlPath": "/gravitee-log*/_search"
      }
     ]
    },
    {
     "title": "Pour trajets ponctuels demandés par des passagers",
     "type": "bargauge",
     "description": "Par palier de nombre de trajets retournés, ce graphe présente le nombre de recherches de trajets ponctuels demandés par les passagers.",
     "gridPos": { "h": 9, "w": 12, "x": 11, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "body": "{\r\n  \"size\": 0,\r\n  \"aggs\": {\r\n    \"response-size\": {\r\n      \"range\": {\r\n        \"field\": \"client-response.headers.X-RESPONSE-SIZE\",\r\n        \"ranges\": [\r\n          {\r\n            \"key\": \"totalNonNull\",\r\n            \"from\": 1\r\n          },\r\n          {\r\n            \"key\": \"Null\",\r\n            \"from\": 0,\r\n            \"to\": 1\r\n          },\r\n          {\r\n            \"key\": \"faible\",\r\n            \"from\": 1,\r\n            \"to\": 6\r\n          },\r\n          {\r\n            \"key\": \"moyen\",\r\n            \"from\": 6,\r\n            \"to\": 11\r\n          },\r\n          {\r\n            \"key\": \"Haut\",\r\n            \"from\": 11\r\n          }\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  \"runtime_mappings\": {\r\n    \"client-response.headers.X-MAPPED-PATH\": {\r\n      \"type\": \"keyword\"\r\n    },\r\n    \"client-response.headers.X-RESPONSE-SIZE\": {\r\n      \"type\": \"long\"\r\n    }\r\n  },\r\n    \"query\": {\r\n    \"bool\": {\r\n      \"filter\": [\r\n        {\r\n          \"range\": {\r\n            \"client-response.status\": {\r\n              \"lt\": 299,\r\n              \"gte\": 200\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"bool\": {\r\n            \"should\": [\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"client-response.headers.X-MAPPED-PATH\": \"/partners/:partnerId/carpooling/passenger_journeys\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              }\r\n            ],\r\n            \"minimum_should_match\": 1\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n               \"gte\": \"${__from:date:iso}\",\r\n              \"lt\": \"${__to:date:iso}\"\r\n            }\r\n          }\r\n        }\r\n      ],\r\n      \"should\": [],\r\n      \"must_not\": []\r\n    }\r\n  }\r\n}",
       "fields": [
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"Null\")].doc_count",
         "name": "0 trajet"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"faible\")].doc_count",
         "language": "jsonpath",
         "name": "Entre 1 et 5 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"moyen\")].doc_count",
         "language": "jsonpath",
         "name": "Entre 6 et 10 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"Haut\")].doc_count",
         "language": "jsonpath",
         "name": "Supérieur à 10 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"totalNonNull\")].doc_count",
         "language": "jsonpath",
         "name": "Total recherches avec au moins 1 trajet"
        }
       ],
       "method": "POST",
       "urlPath": "/gravitee-log*/_search"
      }
     ]
    },
    {
     "title": "Pour trajets réguliers proposés par des conducteurs",
     "type": "bargauge",
     "description": "Par palier de nombre de trajets retournés, ce graphe présente le nombre de recherches de trajets réguliers proposés par les conducteurs.",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 54 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "body": "{\r\n  \"size\": 0,\r\n  \"aggs\": {\r\n    \"response-size\": {\r\n      \"range\": {\r\n        \"field\": \"client-response.headers.X-RESPONSE-SIZE\",\r\n        \"ranges\": [\r\n           {\r\n            \"key\": \"totalNonNull\",\r\n            \"from\": 1\r\n          },\r\n          {\r\n            \"key\": \"Null\",\r\n            \"from\": 0,\r\n            \"to\": 1\r\n          },\r\n          {\r\n            \"key\": \"faible\",\r\n            \"from\": 1,\r\n            \"to\": 6\r\n          },\r\n          {\r\n            \"key\": \"moyen\",\r\n            \"from\": 6,\r\n            \"to\": 11\r\n          },\r\n          {\r\n            \"key\": \"Haut\",\r\n            \"from\": 11\r\n          }\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  \"runtime_mappings\": {\r\n    \"client-response.headers.X-MAPPED-PATH\": {\r\n      \"type\": \"keyword\"\r\n    },\r\n    \"client-response.headers.X-RESPONSE-SIZE\": {\r\n      \"type\": \"long\"\r\n    }\r\n  },\r\n    \"query\": {\r\n    \"bool\": {\r\n      \"filter\": [\r\n        {\r\n          \"range\": {\r\n            \"client-response.status\": {\r\n              \"lt\": 299,\r\n              \"gte\": 200\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"bool\": {\r\n            \"should\": [\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"client-response.headers.X-MAPPED-PATH\": \"/partners/:partnerId/carpooling/driver_regular_trips\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              }\r\n            ],\r\n            \"minimum_should_match\": 1\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n               \"gte\": \"${__from:date:iso}\",\r\n              \"lt\": \"${__to:date:iso}\"\r\n            }\r\n          }\r\n        }\r\n      ],\r\n      \"should\": [],\r\n      \"must_not\": []\r\n    }\r\n  }\r\n}",
       "fields": [
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"Null\")].doc_count",
         "name": "0 trajet"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"faible\")].doc_count",
         "language": "jsonpath",
         "name": "Entre 1 et 5 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"moyen\")].doc_count",
         "language": "jsonpath",
         "name": "Entre 6 et 10 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"Haut\")].doc_count",
         "language": "jsonpath",
         "name": "Supérieur à 10 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"totalNonNull\")].doc_count",
         "language": "jsonpath",
         "name": "Total recherches avec au moins 1 trajet"
        }
       ],
       "method": "POST",
       "urlPath": "/gravitee-log*/_search"
      }
     ]
    },
    {
     "title": "Pour trajets réguliers demandés par des passagers",
     "type": "bargauge",
     "description": "Par palier de nombre de trajets retournés, ce graphe présente le nombre de recherches de trajets réguliers demandés par les passagers.",
     "gridPos": { "h": 9, "w": 12, "x": 11, "y": 54 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "body": "{\r\n  \"size\": 0,\r\n  \"aggs\": {\r\n    \"response-size\": {\r\n      \"range\": {\r\n        \"field\": \"client-response.headers.X-RESPONSE-SIZE\",\r\n        \"ranges\": [\r\n          {\r\n            \"key\": \"totalNonNull\",\r\n            \"from\": 1\r\n          },\r\n          {\r\n            \"key\": \"Null\",\r\n            \"from\": 0,\r\n            \"to\": 1\r\n          },\r\n          {\r\n            \"key\": \"faible\",\r\n            \"from\": 1,\r\n            \"to\": 6\r\n          },\r\n          {\r\n            \"key\": \"moyen\",\r\n            \"from\": 6,\r\n            \"to\": 11\r\n          },\r\n          {\r\n            \"key\": \"Haut\",\r\n            \"from\": 11\r\n          }\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  \"runtime_mappings\": {\r\n    \"client-response.headers.X-MAPPED-PATH\": {\r\n      \"type\": \"keyword\"\r\n    },\r\n    \"client-response.headers.X-RESPONSE-SIZE\": {\r\n      \"type\": \"long\"\r\n    }\r\n  },\r\n    \"query\": {\r\n    \"bool\": {\r\n      \"filter\": [\r\n        {\r\n          \"range\": {\r\n            \"client-response.status\": {\r\n              \"lt\": 299,\r\n              \"gte\": 200\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"bool\": {\r\n            \"should\": [\r\n              {\r\n                \"bool\": {\r\n                  \"should\": [\r\n                    {\r\n                      \"match_phrase\": {\r\n                        \"client-response.headers.X-MAPPED-PATH\": \"/partners/:partnerId/carpooling/passenger_regular_trips\"\r\n                      }\r\n                    }\r\n                  ],\r\n                  \"minimum_should_match\": 1\r\n                }\r\n              }\r\n            ],\r\n            \"minimum_should_match\": 1\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n               \"gte\": \"${__from:date:iso}\",\r\n              \"lt\": \"${__to:date:iso}\"\r\n            }\r\n          }\r\n        }\r\n      ],\r\n      \"should\": [],\r\n      \"must_not\": []\r\n    }\r\n  }\r\n}",
       "fields": [
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"Null\")].doc_count",
         "name": "0 trajet"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"faible\")].doc_count",
         "language": "jsonpath",
         "name": "Entre 1 et 5 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"moyen\")].doc_count",
         "language": "jsonpath",
         "name": "Entre 6 et 10 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"Haut\")].doc_count",
         "language": "jsonpath",
         "name": "Supérieur à 10 trajets"
        },
        {
         "jsonPath": "$.aggregations.response-size.buckets[?(@.key == \"totalNonNull\")].doc_count",
         "language": "jsonpath",
         "name": "Total recherches avec au moins 1 trajet"
        }
       ],
       "method": "POST",
       "urlPath": "/gravitee-log*/_search"
      }
     ]
    }
   ]
  },
  {
   "title": "Informations Identifiants ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Applications clientes de Gravitee",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 46 },
     "targets": [
      {
       "rawSql": "select name, id  from applications where status = 'ACTIVE';"
      },
      {
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "Partners",
     "type": "table",
     "gridPos": { "h": 8, "w": 13, "x": 10, "y": 46 },
     "targets": [
      {
       "rawSql": "select pm.\"name\", pm.partner_type as \"Msp/MaaS\", partner_id from \r\nmsp.partner_meta pm \r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Informations techniques Analytics Gravitee",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "driver_journeys",
     "type": "table",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 47 },
     "targets": [
      {
       "body": "{\r\n  \"size\": 0,\r\n  \"query\": {\r\n    \"bool\": {\r\n      \"must\": [\r\n        {\r\n          \"query_string\": {\r\n            \"default_field\": \"path\",\r\n            \"query\": \"*\\\\/${partner_id}*\"\r\n          }\r\n        },{\r\n          \"query_string\": {\r\n            \"query\": \"\\\\/partners\\\\/\\\\:partnerId\\\\/carpooling\\\\/driver_journeys\",\r\n            \"fields\": [\r\n              \"mapped-path\"\r\n            ]\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"${__from:date:iso}\",\r\n              \"lt\": \"${__to:date:iso}\"\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  \"aggs\": {\r\n    \"by_endpoint\": {\r\n      \"terms\": {\r\n        \"field\": \"mapped-path\"\r\n      },\r\n      \"aggs\": {\r\n        \"by-status\": {\r\n          \"terms\": {\r\n            \"field\": \"status\"\r\n          }\r\n        }\r\n      }\r\n    }\r\n  }\r\n}",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "fields": [
        {
         "jsonPath": "$.aggregations.by_endpoint.buckets[?(@.key=\"/partners/:partnerId/carpooling/driver_journeys\")].by-status.buckets[*].doc_count",
         "language": "jsonpath",
         "name": "Nombre d'appels"
        },
        {
         "jsonPath": "$.aggregations.by_endpoint.buckets[?(@.key=\"/partners/:partnerId/carpooling/driver_journeys\")].by-status.buckets[*].key",
         "language": "jsonpath",
         "name": "Status",
         "type": "number"
        }
       ],
       "headers": [
        [
         "Content-Type",
         "application/json"
        ]
       ],
       "method": "POST",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp",
       "urlPath": "/gravitee-request*/_search"
      }
     ]
    },
    {
     "title": "passenger_journeys",
     "type": "table",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 47 },
     "targets": [
      {
       "body": "{\r\n  \"size\": 0,\r\n  \"query\": {\r\n    \"bool\": {\r\n      \"must\": [\r\n        {\r\n          \"query_string\": {\r\n            \"default_field\": \"path\",\r\n            \"query\": \"*\\\\/${partner_id}*\"\r\n          }\r\n        },{\r\n          \"query_string\": {\r\n            \"query\": \"\\\\/partners\\\\/\\\\:partnerId\\\\/carpooling\\\\/passenger_journeys\",\r\n            \"fields\": [\r\n              \"mapped-path\"\r\n            ]\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"${__from:date:iso}\",\r\n              \"lt\": \"${__to:date:iso}\"\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  \"aggs\": {\r\n    \"by_endpoint\": {\r\n      \"terms\": {\r\n        \"field\": \"mapped-path\"\r\n      },\r\n      \"aggs\": {\r\n        \"by-status\": {\r\n          \"terms\": {\r\n            \"field\": \"status\"\r\n          }\r\n        }\r\n      }\r\n    }\r\n  }\r\n}",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "fields": [
        {
         "jsonPath": "$.aggregations.by_endpoint.buckets[?(@.key=\"/partners/:partnerId/carpooling/passenger_journeys\")].by-status.buckets[*].doc_count",
         "language": "jsonpath",
         "name": "Nombre d'appels"
        },
        {
         "jsonPath": "$.aggregations.by_endpoint.buckets[?(@.key=\"/partners/:partnerId/carpooling/passenger_journeys\")].by-status.buckets[*].key",
         "language": "jsonpath",
         "name": "Status",
         "type": "number"
        }
       ],
       "headers": [
        [
         "Content-Type",
         "application/json"
        ]
       ],
       "method": "POST",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp",
       "urlPath": "/gravitee-request*/_search"
      }
     ]
    },
    {
     "title": "driver_regular_trips",
     "type": "table",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 51 },
     "targets": [
      {
       "body": "{\r\n  \"size\": 0,\r\n  \"query\": {\r\n    \"bool\": {\r\n      \"must\": [\r\n        {\r\n          \"query_string\": {\r\n            \"default_field\": \"path\",\r\n            \"query\": \"*\\\\/${partner_id}*\"\r\n          }\r\n        },{\r\n          \"query_string\": {\r\n            \"query\": \"\\\\/partners\\\\/\\\\:partnerId\\\\/carpooling\\\\/driver_regular_trips\",\r\n            \"fields\": [\r\n              \"mapped-path\"\r\n            ]\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"${__from:date:iso}\",\r\n              \"lt\": \"${__to:date:iso}\"\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  \"aggs\": {\r\n    \"by_endpoint\": {\r\n      \"terms\": {\r\n        \"field\": \"mapped-path\"\r\n      },\r\n      \"aggs\": {\r\n        \"by-status\": {\r\n          \"terms\": {\r\n            \"field\": \"status\"\r\n          }\r\n        }\r\n      }\r\n    }\r\n  }\r\n}",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "fields": [
        {
         "jsonPath": "$.aggregations.by_endpoint.buckets[?(@.key=\"/partners/:partnerId/carpooling/driver_regular_trips\")].by-status.buckets[*].doc_count",
         "language": "jsonpath",
         "name": "Nombre d'appels"
        },
        {
         "jsonPath": "$.aggregations.by_endpoint.buckets[?(@.key=\"/partners/:partnerId/carpooling/driver_regular_trips\")].by-status.buckets[*].key",
         "language": "jsonpath",
         "name": "Status",
         "type": "number"
        }
       ],
       "headers": [
        [
         "Content-Type",
         "application/json"
        ]
       ],
       "method": "POST",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp",
       "urlPath": "/gravitee-request*/_search"
      }
     ]
    },
    {
     "title": "passenger_regular_trips",
     "type": "table",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 51 },
     "targets": [
      {
       "body": "{\r\n  \"size\": 0,\r\n  \"query\": {\r\n    \"bool\": {\r\n      \"must\": [\r\n        {\r\n          \"query_string\": {\r\n            \"default_field\": \"path\",\r\n            \"query\": \"*\\\\/${partner_id}*\"\r\n          }\r\n        },{\r\n          \"query_string\": {\r\n            \"query\": \"\\\\/partners\\\\/\\\\:partnerId\\\\/carpooling\\\\/passenger_regular_trips\",\r\n            \"fields\": [\r\n              \"mapped-path\"\r\n            ]\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"${__from:date:iso}\",\r\n              \"lt\": \"${__to:date:iso}\"\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  \"aggs\": {\r\n    \"by_endpoint\": {\r\n      \"terms\": {\r\n        \"field\": \"mapped-path\"\r\n      },\r\n      \"aggs\": {\r\n        \"by-status\": {\r\n          \"terms\": {\r\n            \"field\": \"status\"\r\n          }\r\n        }\r\n      }\r\n    }\r\n  }\r\n}",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "fields": [
        {
         "jsonPath": "$.aggregations.by_endpoint.buckets[?(@.key=\"/partners/:partnerId/carpooling/passenger_regular_trips\")].by-status.buckets[*].doc_count",
         "language": "jsonpath",
         "name": "Nombre d'appels"
        },
        {
         "jsonPath": "$.aggregations.by_endpoint.buckets[?(@.key=\"/partners/:partnerId/carpooling/passenger_regular_trips\")].by-status.buckets[*].key",
         "language": "jsonpath",
         "name": "Status",
         "type": "number"
        }
       ],
       "headers": [
        [
         "Content-Type",
         "application/json"
        ]
       ],
       "method": "POST",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp",
       "urlPath": "/gravitee-request*/_search"
      }
     ]
    }
   ]
  },
  {
   "title": "Temps moyen  de réponse par jour ( Temps entre l'appel du MAAS et la réponse fournie )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": " $endpoints",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "repeat": "endpoints",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "body": "{\r\n  \"size\":0,\r\n  \"query\": {\r\n    \"bool\": {\r\n      \"must\": [\r\n        {\r\n          \"query_string\": {\r\n            \"default_field\": \"path\",\r\n            \"query\": \"*\\\\/${partner_id}*\"\r\n          }\r\n        },{\r\n          \"query_string\": {\r\n            \"query\": $endpoints,\r\n            \"fields\": [\r\n              \"mapped-path\"\r\n            ]\r\n          }\r\n        },\r\n        {\r\n          \"query_string\": {\r\n            \"query\": \"200\",\r\n            \"fields\": [\r\n              \"status\"\r\n            ]\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"${__from:date:iso}\",\r\n              \"lt\": \"${__to:date:iso}\"\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  \"aggs\": {\r\n    \"my-date-histogram\": {\r\n      \"date_histogram\": {\r\n        \"field\": \"@timestamp\",\r\n        \"calendar_interval\": \"1d\",\r\n        \"time_zone\": \"Europe/Paris\",\r\n        \"min_doc_count\": 0,\r\n        \"extended_bounds\": {\r\n          \"min\": \"${__from:date:iso}\",\r\n          \"max\": \"${__to:date:iso}\"\r\n        },\r\n        \"order\": {\r\n          \"_key\": \"asc\"\r\n        }\r\n      },\r\n      \"aggs\": {\r\n        \"avg-response-time\": {\r\n          \"avg\": {\r\n            \"field\": \"response-time\"\r\n          }\r\n        }\r\n      }\r\n    }\r\n  }\r\n\r\n  \r\n}",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "fields": [
        {
         "jsonPath": "$.aggregations.my-date-histogram.buckets[*].key",
         "language": "jsonpath",
         "name": "jour",
         "type": "time"
        },
        {
         "jsonPath": "$.aggregations.my-date-histogram.buckets[*].avg-response-time.value",
         "language": "jsonpath",
         "name": "temps moyen de réponse",
         "type": "number"
        }
       ],
       "headers": [
        [
         "Content-Type",
         "application/json"
        ]
       ],
       "method": "POST",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp",
       "urlPath": "/gravitee-request*/_search"
      }
     ]
    },
    {
     "title": "Temps moyen des réponses (en ms)",
     "type": "barchart",
     "gridPos": { "h": 13, "w": 20, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "body": "{\r\n  \"aggs\": {\r\n    \"endpoints\": {\r\n      \"terms\": {\r\n        \"field\": \"mapped-path\",\r\n        \"order\": {\r\n          \"avg-response-time\": \"desc\"\r\n        },\r\n        \"size\": 50\r\n      },\r\n      \"aggs\": {\r\n        \"avg-response-time\": {\r\n          \"avg\": {\r\n            \"field\": \"response-time\"\r\n          }\r\n        }\r\n      }\r\n    }\r\n  },\r\n  \"size\": 0,\r\n  \"script_fields\": {},\r\n  \"stored_fields\": [\r\n    \"*\"\r\n  ],\r\n  \"runtime_mappings\": {},\r\n  \"query\": {\r\n    \"bool\": {\r\n      \"must\": [],\r\n      \"filter\": [\r\n        {\r\n          \"range\": {\r\n            \"status\": {\r\n              \"lt\": 299,\r\n              \"gte\": 200\r\n            }\r\n          }\r\n        },\r\n        {\r\n           \"query_string\": {\r\n            \"default_field\": \"path\",\r\n            \"query\": \"*\\\\/${partner_id}*\"\r\n          }\r\n        },\r\n         {\r\n           \"query_string\": {\r\n            \"default_field\": \"uri\",\r\n            \"query\": \"\\\\/api\\\\/*\"\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"format\": \"strict_date_optional_time\",\r\n              \"gte\": \"${__from:date:iso}\",\r\n              \"lt\": \"${__to:date:iso}\"\r\n            }\r\n          }\r\n        }\r\n      ],\r\n      \"should\": [],\r\n      \"must_not\": []\r\n    }\r\n  }\r\n}",
       "fields": [
        {
         "jsonPath": "$.aggregations.endpoints.buckets[*].key",
         "language": "jsonpath",
         "type": "string"
        },
        {
         "jsonPath": "$.aggregations.endpoints.buckets[*].avg-response-time.value",
         "language": "jsonpath",
         "name": "",
         "type": "number"
        }
       ],
       "method": "POST",
       "urlPath": "/gravitee-request-*/_search?size=0"
      }
     ]
    }
   ]
  },
  {
   "title": "Temps de réponse moyen par mois ( Temps entre l'appel du MAAS et la réponse fournie )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": " $endpoints",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
     "repeat": "endpoints",
     "targets": [
      {
       "body": "{\r\n  \"size\":0,\r\n  \"query\": {\r\n    \"bool\": {\r\n      \"must\": [\r\n        {\r\n          \"query_string\": {\r\n            \"default_field\": \"path\",\r\n            \"query\": \"*\\\\/${partner_id}*\"\r\n          }\r\n        },{\r\n          \"query_string\": {\r\n            \"query\": $endpoints,\r\n            \"fields\": [\r\n              \"mapped-path\"\r\n            ]\r\n          }\r\n        },\r\n        {\r\n          \"query_string\": {\r\n            \"query\": \"200\",\r\n            \"fields\": [\r\n              \"status\"\r\n            ]\r\n          }\r\n        },\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"${__from:date:iso}\",\r\n              \"lt\": \"${__to:date:iso}\"\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  \"aggs\": {\r\n    \"my-date-histogram\": {\r\n      \"date_histogram\": {\r\n        \"field\": \"@timestamp\",\r\n        \"calendar_interval\": \"1M\",\r\n        \"time_zone\": \"Europe/Paris\",\r\n        \"min_doc_count\": 0,\r\n        \"extended_bounds\": {\r\n          \"min\": \"${__from:date:iso}\",\r\n          \"max\": \"${__to:date:iso}\"\r\n        },\r\n        \"order\": {\r\n          \"_key\": \"asc\"\r\n        }\r\n      },\r\n      \"aggs\": {\r\n        \"avg-response-time\": {\r\n          \"avg\": {\r\n            \"field\": \"response-time\"\r\n          }\r\n        }\r\n      }\r\n    }\r\n  }\r\n}",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "fields": [
        {
         "jsonPath": "$.aggregations.my-date-histogram.buckets[*].key_as_string",
         "language": "jsonpath",
         "name": "jour",
         "type": "time"
        },
        {
         "jsonPath": "$.aggregations.my-date-histogram.buckets[*].avg-response-time.value",
         "language": "jsonpath",
         "name": "Temps moyen de réponse",
         "type": "number"
        }
       ],
       "headers": [
        [
         "Content-Type",
         "application/json"
        ]
       ],
       "method": "POST",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp",
       "urlPath": "/gravitee-request*/_search"
      }
     ]
    }
   ]
  }
 ]
}