
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    select ('base de données démarrée') as status;
    CREATE SCHEMA IF NOT EXISTS msp;
    CREATE SCHEMA IF NOT EXISTS configuration;

    CREATE USER "$POSTGRES_SERVICE_USER" WITH PASSWORD '$POSTGRES_SERVICE_PASSWORD';
    begin;
      GRANT CONNECT ON DATABASE $POSTGRES_DB TO "$POSTGRES_SERVICE_USER";
      GRANT USAGE ON SCHEMA msp TO "$POSTGRES_SERVICE_USER";
      GRANT USAGE, CREATE ON SCHEMA msp TO "$POSTGRES_SERVICE_USER";
      GRANT ALL ON ALL TABLES IN SCHEMA msp TO "$POSTGRES_SERVICE_USER";
      GRANT ALL ON ALL SEQUENCES IN SCHEMA msp TO "$POSTGRES_SERVICE_USER";
      ALTER DEFAULT PRIVILEGES IN SCHEMA msp GRANT SELECT ON TABLES TO "$POSTGRES_SERVICE_USER";

      GRANT USAGE ON SCHEMA configuration TO "$POSTGRES_SERVICE_USER";
      GRANT USAGE, CREATE ON SCHEMA configuration TO "$POSTGRES_SERVICE_USER";
      GRANT ALL ON ALL TABLES IN SCHEMA configuration TO "$POSTGRES_SERVICE_USER";
      GRANT ALL ON ALL SEQUENCES IN SCHEMA configuration TO "$POSTGRES_SERVICE_USER";
      ALTER DEFAULT PRIVILEGES IN SCHEMA configuration GRANT SELECT ON TABLES TO "$POSTGRES_SERVICE_USER";
    commit;
    select ('utilisateur $POSTGRES_SERVICE_USER créé') as creation_status;
EOSQL
