# --- Function helpers to deploy and wait for module dependencies---
.env_preview:
  environment:
    name: $CI_COMMIT_REF_SLUG-$LANDSCAPE/$MODULE_NAME

.helm-deploy-preview-job:
  extends:
    - .helm-deploy-job
    - .helm-deploy-preview-tags
    - .dev_pipeline_condition
    - .no-needs
    - .env_preview
  when: manual
  variables:
    LANDSCAPE: preview-gw
    OPS_PIPELINE_CONDITION: "false"

api_helm_deploy_preview:
  stage: deploy-preview
  extends:
    - .helm-deploy-preview-job
  variables:
    MODULE_NAME: api
  script:
    - |
      set -x
      . env/deployment.env
      get_release_name
      . env/.env.preview
      helm_deploy $MODULE_NAME

data_api_helm_deploy_preview:
  stage: deploy-preview
  extends:
    - .helm-deploy-preview-job
  variables:
    MODULE_NAME: data-api
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.preview
      helm_deploy $MODULE_NAME

routing_api_helm_deploy_preview:
  stage: deploy-preview
  extends:
    - .helm-deploy-preview-job
  variables:
    MODULE_NAME: routing-api
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.preview
      helm_deploy $MODULE_NAME

request_relay_helm_deploy_preview:
  stage: deploy-preview
  extends:
    - .helm-deploy-preview-job
  variables:
    MODULE_NAME: request-relay
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.preview
      helm_deploy $MODULE_NAME

default_adapter_deploy_preview:
  stage: deploy-preview
  extends:
    - .helm-deploy-preview-job
  variables:
    MODULE_NAME: default-adapter
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.preview
      helm_deploy $MODULE_NAME

custom_adapter_helm_deploy_preview:
  stage: deploy-preview
  extends:
    - .helm-deploy-preview-job
  variables:
    MODULE_NAME: custom-adapter
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.preview
      helm_deploy $MODULE_NAME

# gravitee_apim_helm_deploy_preview:
#   stage: deploy-preview
#   extends:
#     - .helm-deploy-preview-job
#     - .no-needs
#     - .env_preview
#   variables:
#     MODULE_NAME: gravitee-apim
#   when: manual
#   script:
#     - |
#       set -x
#       . env/.env.preview
#       helm_deploy $MODULE_NAME

cache_manager_deploy_preview:
  stage: deploy-preview
  extends:
    - .helm-deploy-preview-job
  variables:
    MODULE_NAME: cache-manager
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.preview
      helm_deploy $MODULE_NAME

mock_api_deploy_preview:
  stage: deploy-preview
  extends:
    - .helm-deploy-preview-job
  variables:
    MODULE_NAME: mock-api
    COMPUTED_MOCK_RESPONSES_DIRECTORY: ${GITLAB_MOCK_RESPONSES_DIRECTORY:-/mocks}
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.preview
      export COMPUTED_MOCK_RESPONSES_DIRECTORY=${GITLAB_MOCK_RESPONSES_DIRECTORY:-/mocks}
      helm_deploy $MODULE_NAME

dkron_deploy_preview:
  stage: deploy-preview
  extends:
    - .helm-deploy-preview-job
  variables:
    MODULE_NAME: dkron
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.preview
      helm_deploy $MODULE_NAME

elasticsearch_helm_deploy_preview:
  stage: deploy-preview
  extends:
    - .helm-deploy-preview-job
    - .no-needs
    - .always
    - .env_preview
  when: always
  variables:
    MODULE_NAME: elasticsearch
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.preview
      helm_deploy $MODULE_NAME

apm_and_kibana_helm_deploy_preview:
  stage: deploy-preview
  extends:
    - .helm-deploy-preview-job
    - .no-needs
    - .always
    - .env_preview
  variables:
    MODULE_NAME: apm
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.preview
      helm_deploy $MODULE_NAME

gravitee_apim_helm_deploy_preview:
  stage: deploy-preview
  extends:
    - .helm-deploy-preview-job
    - .no-needs
    - .always
    - .env_preview
  when: always
  variables:
    MODULE_NAME: gravitee-apim
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.preview
      helm_deploy $MODULE_NAME