# --- Function helpers to deploy and wait for module dependencies---
.env_testing:
  environment:
    name: $CI_COMMIT_REF_SLUG-$LANDSCAPE/$MODULE_NAME

.helm-deploy-testing-job:
  extends:
    - .helm-deploy-job
    - .helm-deploy-testing-tags
    - .dev_pipeline_condition
    - .no-needs
    - .env_testing
  when: manual
  variables:
    LANDSCAPE: testing-gw
    OPS_PIPELINE_CONDITION: "false"

api_helm_deploy_testing:
  stage: deploy-testing
  extends:
    - .helm-deploy-testing-job
  variables:
    MODULE_NAME: api
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.testing
      helm_deploy $MODULE_NAME
      

data_api_helm_deploy_testing:
  stage: deploy-testing
  extends:
    - .helm-deploy-testing-job
  variables:
    MODULE_NAME: data-api
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.testing
      helm_deploy $MODULE_NAME

routing_api_helm_deploy_testing:
  stage: deploy-testing
  extends:
    - .helm-deploy-testing-job
  variables:
    MODULE_NAME: routing-api
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.testing
      helm_deploy $MODULE_NAME

request_relay_helm_deploy_testing:
  stage: deploy-testing
  extends:
    - .helm-deploy-testing-job
  variables:
    MODULE_NAME: request-relay
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.testing
      helm_deploy $MODULE_NAME

default_adapter_deploy_testing:
  stage: deploy-testing
  extends:
    - .helm-deploy-testing-job
  variables:
    MODULE_NAME: default-adapter
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.testing
      helm_deploy $MODULE_NAME

custom_adapter_helm_deploy_testing:
  stage: deploy-testing
  extends:
    - .helm-deploy-testing-job
  variables:
    MODULE_NAME: custom-adapter
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.testing
      helm_deploy $MODULE_NAME

gravitee_apim_helm_deploy_testing:
  stage: deploy-testing
  extends:
    - .helm-deploy-testing-job
    - .no-needs
    - .always
    - .env_testing
  variables:
    MODULE_NAME: gravitee-apim
  script:
    - |
      set -x
      . env/.env.testing
      helm_deploy $MODULE_NAME

cache_manager_deploy_testing:
  stage: deploy-testing
  extends:
    - .helm-deploy-testing-job
  variables:
    MODULE_NAME: cache-manager
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.testing
      helm_deploy $MODULE_NAME

mock_api_deploy_testing:
  stage: deploy-testing
  extends:
    - .helm-deploy-testing-job
  variables:
    MODULE_NAME: mock-api
    COMPUTED_MOCK_RESPONSES_DIRECTORY: ${GITLAB_MOCK_RESPONSES_DIRECTORY:-/mocks}
  script:
    - |
      . env/deployment.env
      get_release_name
      . env/.env.testing
      helm_deploy $MODULE_NAME

dkron_deploy_testing:
  stage: deploy-testing
  extends:
    - .helm-deploy-testing-job
  variables:
    MODULE_NAME: dkron
  script:
    - |
      get_release_name
      . env/.env.testing
      helm_deploy $MODULE_NAME