include:
  - local: "adapters/default-adapter/.gitlab-ci/helm.yml"

.default-adapter-base:
  variables:
    MODULE_NAME: default-adapter
    MODULE_PATH: adapters/${MODULE_NAME}
    NEXUS_MAVEN_IMAGE_NAME: ${NEXUS_DOCKER_REGISTRY}/library/adoptopenjdk:11-jre-hotspot

.default_adapter_init_vars: &default_adapter_init_vars |
  export GITLAB_IMAGE_PULL_SECRET_NAME=${IMAGE_PULL_SECRET_PREFIX}-${MODULE_NAME}
  export DEFAULT_ADAPTER_IMAGE_NAME=${REGISTRY_BASE_NAME}/default-adapter:${IMAGE_TAG_NAME}
  export BASE_DEFAULT_ADAPTER_IMAGE_NAME=${NEXUS_MAVEN_IMAGE_NAME}
  export MODULE_NAME=${MODULE_NAME}
  export MODULE_PATH=${MODULE_PATH}
  echo "BASE_DEFAULT_ADAPTER_IMAGE_NAME=$BASE_DEFAULT_ADAPTER_IMAGE_NAME"
  echo "MODULE_PATH=${MODULE_PATH}"
  echo "MODULE_NAME=${MODULE_PATH}"
  export VERSION=`cat pom.xml | grep "<groupId>com.gateway</groupId>" -C 3 | grep -E  "<version>.*</version>" -o | head -1 | sed -E "s/<version>(.*)<\/version>/\1/g" | sed -E "s/-SNAPSHOT/-${BRANCH_NAME}-SNAPSHOT/g"`

.default-adapter-build: &default-adapter-build |
  set -x
  envsubst < settings.xml
  # if release version we change pom version with the new version
  if [ ! -z $NEW_RELEASE_VERSION ]
  then
    mvn  --batch-mode -s settings.xml versions:set -DprocessAllModules -DgenerateBackupPoms=false -DnewVersion=$NEW_RELEASE_VERSION
  fi
  cd adapters/default-adapter
  envsubst < ../../settings.xml
  mvn clean install -s ../../settings.xml -DskipTests -Dlogging.level.org.springframework=INFO -Dlogging.level.com.gateway=INFO

default_adapter_build:
  extends:
    - .default-adapter-base
    - .build-job
    - .no-needs
    - .envsubst
  environment:
    name: ${CI_BUILD_REF_SLUG}/default-adapter
  script:
    - *default_adapter_init_vars
    - *default-adapter-build
  artifacts:
    paths:
      - adapters/default-adapter/target
  needs: [ "deploy-nexus", "check-if-release-version" ]

default_adapter_image_build:
  extends:
    - .image-job
    - .default-adapter-base
  environment:
    name: image/${CI_BUILD_REF_SLUG}/default-adapter
  script:
    - *default_adapter_init_vars
    - |
      cp ../../delivery/commons/lib/elastic-apm-agent-1.35.0.jar .
      image
  needs: [ "default_adapter_build" , "check-if-release-version" ]


default_adapter_preview_deploy:
  extends:
    - .preview-deploy-job
    - .default-adapter-base
  script:
    - *default_adapter_init_vars
    - |
      deploy
  needs: [ "default_adapter_image_build", "check-if-release-version" ]
  environment:
    on_stop: default_adapter_preview_cleanup


default_adapter_preview_cleanup:
  extends:
    - .preview-undeploy-job
    - .default-adapter-base
  script:
    - |
      undeploy
      
      #TODO artifact entre ressource.yml deploiement et undeploy