{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .metadata.name }}
  annotations:
   {{- with .metadata.annotations }}
   {{- toYaml . | nindent 4 }}
   {{- end }}
  labels:
  {{- with .metadata.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
   {{- with .spec }}
   {{- toYaml . | nindent 4 }}
   {{- end }}
status:
   {{- with .status }}
   {{- toYaml . | nindent 4 }}
   {{- end }}
{{- end }}
