# CREATE SERVICE USER WITH READ ACCESS RIGHT ON SCHEMA
# REPLACE VARIABLES WITH ONE FROM GITLAB CI

set -e

psql -v ON_ERROR_STOP=1 -h "$DATABASE_NAME" --username "$CLOUD_POSTGRES_ROOT_USER" --dbname "$CLOUD_POSTGRES_ROOT_DB" <<-EOSQL
    CREATE SCHEMA IF NOT EXISTS msp;
    CREATE SCHEMA IF NOT EXISTS configuration;
    CREATE USER "$POSTGRES_SERVICE_USER" WITH PASSWORD '$POSTGRES_SERVICE_PASSWORD';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO "$POSTGRES_SERVICE_USER";
    GRANT USAGE ON SCHEMA msp TO "$POSTGRES_SERVICE_USER";
    GRANT USAGE, CREATE ON SCHEMA msp TO "$POSTGRES_SERVICE_USER";
    GRANT ALL ON ALL TABLES IN SCHEMA msp TO "$POSTGRES_SERVICE_USER";
    GRANT ALL ON ALL SEQUENCES IN SCHEMA msp TO "$POSTGRES_SERVICE_USER";
    ALTER DEFAULT PRIVILEGES IN SCHEMA msp GRANT SELECT ON TABLES TO "$POSTGRES_SERVICE_USER";
    GRANT USAGE ON SCHEMA configuration TO "$POSTGRES_SERVICE_USER";
    GRANT USAGE, CREATE ON SCHEMA configuration TO "$POSTGRES_SERVICE_USER";
    GRANT ALL ON ALL TABLES IN SCHEMA configuration TO "$POSTGRES_SERVICE_USER";
    GRANT ALL ON ALL SEQUENCES IN SCHEMA configuration TO "$POSTGRES_SERVICE_USER";
    ALTER DEFAULT PRIVILEGES IN SCHEMA configuration GRANT SELECT ON TABLES TO "$POSTGRES_SERVICE_USER";
EOSQL