.postgres-base:
  variables:
    MODULE_NAME: postgresgateway
    MODULE_PATH: delivery/${MODULE_NAME}
    NEXUS_POSTGRES_IMAGE_NAME: ${NEXUS_DOCKER_REGISTRY}/postgres:13.6
    DATABASE_NAME: gateway
    DATABASE_USER_NAME: ${POSTGRES_ADMIN_USER}
    DATABASE_USER_PWD: ${POSTGRES_ADMIN_PASSWORD}
    DB_SERVICE_USER: $POSTGRES_SERVICE_USER
    DB_SERVICE_PASSWORD: ${POSTGRES_SERVICE_PASSWORD}
    KUBERNETES_GATEWAY_DB_NAMESPACE: ${KUBERNETES_GATEWAY_DB_NAMESPACE}

.postgres_init_vars: &postgres_init_vars |
  set -x
  export GITLAB_IMAGE_PULL_SECRET_NAME=${IMAGE_PULL_SECRET_PREFIX}-${MODULE_NAME}
  export POSTGRES_IMAGE_NAME=${REGISTRY_BASE_NAME}/postgres:${IMAGE_TAG_NAME}
  export BASE_POSTGRES_IMAGE_NAME=${NEXUS_POSTGRES_IMAGE_NAME}
  export MODULE_NAME=$MODULE_NAME
  export MODULE_PATH=$MODULE_PATH
  export DB_SERVICE_USER
  export DB_SERVICE_PASSWORD

postgres_build:
  extends:
    - .postgres-base
    - .build-job
    - .no-needs
  script:
    - *postgres_init_vars


postgres_image_build:
  extends:
    - .image-job
    - .postgres-base
  script:
    - *postgres_init_vars
    - |
      image
  needs: [ "postgres_build" ]


postgres_preview_deploy:
  extends:
    - .preview-deploy-job
    - .postgres-base
  image: ${KUBETOOLS_IMAGE_TAGNAME}
  script:
    - *postgres_init_vars
    - |
      set -x
      #KUBERNETES_GATEWAY_DB_NAMESPACE=$(pod_namespace postgresgateway)
      #export KUBERNETES_GATEWAY_DB_NAMESPACE
      deploy
      config_volume postgresgateway
  needs: [ "postgres_image_build", "commons-kubetools-image" ]
  environment:
    on_stop: postgres_preview_cleanup


postgres_clear_database:
  extends:
    - .preview-deploy-job
    - .postgres-base
    - .manual
  image: ${KUBETOOLS_IMAGE_TAGNAME}
  script:
    - *postgres_init_vars
    - |
      set -x
      KUBERNETES_GATEWAY_DB_NAMESPACE=$(pod_namespace postgresgateway)
      echo "POSTGRES CLEANING START ${BRANCH_NAME}"
      DB_POD_NAME=$(kubectl get pods -o wide -A | grep `echo $BRANCH_NAME | cut -c -17` | grep postgresgateway | awk '{ print $2 }')
      DB_NAMESPACE=$(kubectl get pods -o wide -A | grep `echo $BRANCH_NAME | cut -c -17` | grep postgresgateway | awk '{ print $1 }')
      kubectl exec $DB_POD_NAME -n $DB_NAMESPACE -c postgresgateway -- sh -c 'psql -U postgres -d gateway -c "TRUNCATE TABLE msp.adapters, msp.body, msp.body_params, msp.cache_param, msp.data_mapper, msp.headers, msp.headers_values_template, msp.msp_actions, msp.msp_calls, msp.msp_meta, msp.msp_standard, msp.params, msp.params_multi_calls, msp.price_list, msp.price_list_item, msp.selector, msp.token CONTINUE IDENTITY CASCADE;"'
  when: manual
  stage: preview-tools
  needs: [ "postgres_preview_deploy" ]

postgres_destroy_database_tables:
  extends:
    - .preview-deploy-job
    - .postgres-base
    - .manual
  image: ${KUBETOOLS_IMAGE_TAGNAME}
  script:
    - *postgres_init_vars
    - |
      set -x
      KUBERNETES_GATEWAY_DB_NAMESPACE=$(pod_namespace postgresgateway)
      echo "POSTGRES CLEANING START ${BRANCH_NAME}"
      DB_POD_NAME=$(kubectl get pods -o wide -A | grep `echo $BRANCH_NAME | cut -c -17` | grep postgresgateway | awk '{ print $2 }')
      DB_NAMESPACE=$(kubectl get pods -o wide -A | grep `echo $BRANCH_NAME | grep postgresgateway | awk '{ print $1 }')
      kubectl exec $DB_POD_NAME -n $DB_NAMESPACE -c postgresgateway -- sh -c 'psql -U postgres -d gateway -c "DROP TABLE msp.adapters, msp.body, msp.body_params, msp.cache_param, msp.data_mapper, msp.headers, msp.headers_values_template, msp.msp_actions, msp.msp_calls, msp.msp_meta, msp.msp_standard, msp.params, msp.params_multi_calls, msp.price_list, msp.price_list_item, msp.selector, msp.token CASCADE;"'
  stage: preview-tools
  needs: [ "postgres_preview_deploy" ]

postgres_preview_cleanup:
  extends:
    - .preview-undeploy-job
    - .postgres-base
  script:
    - |
      delete_volume postgresgateway
      undeploy
      #TODO artifact entre ressource.yml deploiement et undeploy