logging:
  level:
    org:
      springframework: INFO
      springframework.security: INFO
      springframework.web: INFO
      springframework.scheduling.concurrent: WARN
    root: INFO

spring:
  application:
    name: database
  lifecycle:
    timeout-per-shutdown-phase: "10s"
  profiles:
    active: test
  datasource:
    continue-on-error: true
    hikari:
      minimumIdle: 3
      connectionTimeout: 30000
      maximumPoolSize: 12
      idleTimeout: 30000
      poolName: PerimGabaritHikariCP
      maxLifetime: 2000000
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/gateway-tests
    password: ${DATABASE_PASSWORD:@test.database.password@}
    username: ${DATABASE_USERNAME:@test.database.username@}

  jpa:
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2dll:
          create_namespaces: true
        default_schema: msp
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
  data:
    rest:
      basePath: #/api
      detection-strategy: all

