commonAnnotations:
  app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
  app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
  kubernetes.io/ingress.class: traefik

resources:
  - data-api-ingressroute.yml
  # - data-api-certificate.yml
  - data-api-headers-middleware.yml
  - data-api-ratelimit-middleware.yml
  - data-api-inflightreq-middleware.yml

#patchesStrategicMerge:
#  - web_nw_networkpolicy_namespaceselector.yml
