commonAnnotations:
  app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
  app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
  kubernetes.io/ingress.class: traefik

resources:
  - custom-adapter-ingressroute.yml
  # - custom-adapter-certificate.yml
  - custom-adapter-headers-middleware.yml
  - custom-adapter-ratelimit-middleware.yml
  - custom-adapter-inflightreq-middleware.yml

#patchesStrategicMerge:
#  - web_nw_networkpolicy_namespaceselector.yml
