commonAnnotations:
  app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
  app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
  kubernetes.io/ingress.class: traefik

resources:
  - default-adapter-ingressroute.yml
  # - default-adapter-certificate.yml
  - default-adapter-headers-middleware.yml
  - default-adapter-ratelimit-middleware.yml
  - default-adapter-inflightreq-middleware.yml

#patchesStrategicMerge:
#  - web_nw_networkpolicy_namespaceselector.yml
