include:
  - local: "data-api/.gitlab-ci/helm.yml"

.data-api-base:
  variables:
    MODULE_NAME: data-api
    MODULE_PATH: ${MODULE_NAME}
    NEXUS_POSTGRES_IMAGE_NAME: ${NEXUS_DOCKER_REGISTRY}/postgres:13.6
    NEXUS_MAVEN_IMAGE_NAME: ${NEXUS_DOCKER_REGISTRY}/library/adoptopenjdk:11-jre-hotspot
    DATABASE_NAME: gateway
    DATABASE_USER_NAME: ${POSTGRES_SERVICE_USER}
    DATABASE_USER_PWD: ${POSTGRES_SERVICE_PASSWORD}
    KUBERNETES_GATEWAY_DB_NAMESPACE: ${KUBERNETES_GATEWAY_DB_NAMESPACE}


.data_api_init_vars: &data_api_init_vars |
  export GITLAB_IMAGE_PULL_SECRET_NAME=${IMAGE_PULL_SECRET_PREFIX}-${MODULE_NAME}
  export POSTGRES_IMAGE_NAME=${REGISTRY_BASE_NAME}/postgres:${IMAGE_TAG_NAME}
  export BASE_POSTGRES_IMAGE_NAME=${NEXUS_POSTGRES_IMAGE_NAME}
  export DATA_API_IMAGE_NAME=${REGISTRY_BASE_NAME}/data-api:${IMAGE_TAG_NAME}
  export BASE_DATA_API_IMAGE_NAME=${NEXUS_MAVEN_IMAGE_NAME}
  export MODULE_NAME=$MODULE_NAME
  export MODULE_PATH=$MODULE_PATH
  export VERSION=`cat pom.xml | grep "<groupId>com.gateway</groupId>" -C 3 | grep -E  "<version>.*</version>" -o | head -1 | sed -E "s/<version>(.*)<\/version>/\1/g" | sed -E "s/-SNAPSHOT/-${BRANCH_NAME}-SNAPSHOT/g"`

.data-api-build: &data-api-build |
  set -x
  envsubst < settings.xml
  # if release version we change pom version with the new version
  if [ ! -z $NEW_RELEASE_VERSION ]
  then
    mvn  --batch-mode -s settings.xml versions:set -DprocessAllModules -DgenerateBackupPoms=false -DnewVersion=$NEW_RELEASE_VERSION
  fi
  mvn clean install -s settings.xml -DskipTests -Dlogging.level.org.springframework=INFO -Dlogging.level.com.gateway=INFO

data_api_build:
  extends:
    - .data-api-base
    - .build-job
    - .no-needs
    - .envsubst
  environment:
    name: ${CI_BUILD_REF_SLUG}/data-api
  script:
    - *data_api_init_vars
    - *data-api-build
  artifacts:
    paths:
      - data-api/target
  needs: [ "deploy-nexus", "check-if-release-version" ]

data_api_image_build:
  extends:
    - .image-job
    - .data-api-base
  environment:
    name: image/${CI_BUILD_REF_SLUG}/data-api
  script:
    - *data_api_init_vars
    - |
      cp ../delivery/commons/lib/elastic-apm-agent-1.35.0.jar .
      image
  needs: [ "data_api_build" , "check-if-release-version" ]


data_api_preview_deploy:
  extends:
    - .preview-deploy-job
    - .data-api-base
  script:
    - *data_api_init_vars
    - |
      export MAAS_API_CACHE_KEYS_PREFIX="preview"
      deploy
  needs: [ "data_api_image_build", "postgres_preview_deploy"]
  environment:
    on_stop: data_api_preview_cleanup


data_api_preview_cleanup:
  extends:
    - .preview-undeploy-job
    - .data-api-base
  script:
    - |
      undeploy
      
      #TODO artifact entre ressource.yml deploiement et undeploy