version: '3'

services:
  api:
     image: ${API_IMAGE_NAME}
     build:
       context: .
       dockerfile: ./api-dockerfile.yml
       args:
         MAVEN_IMAGE_NAME: ${BASE_API_IMAGE_NAME}
     ports:
       - '8080'
     labels:
       - 'kompose.image-pull-secret=${GITLAB_IMAGE_PULL_SECRET_NAME}'
       - 'kompose.service.type=clusterip'
     environment:
       - SERVICE_BASE_PATH=${API_FQDN}
       - DATA_API_HOST=data-api.data-api-${CI_COMMIT_REF_SLUG}-${LANDSCAPE}.svc.cluster.local
       - ROUTING_API_HOST=routing-api.routing-api-${CI_COMMIT_REF_SLUG}-${LANDSCAPE}.svc.cluster.local
       - MAAS_API_CACHE_HOST=redis.redis-${CI_COMMIT_REF_SLUG}-${LANDSCAPE}.svc.cluster.local
       - MAAS_API_CACHE_PORT=6379
       - MAAS_API_CACHE_KEYS_PREFIX=${MAAS_API_CACHE_KEYS_PREFIX}
       - MAAS_API_CACHE_PASSWORD=${MAAS_API_CACHE_PASSWORD}

# web network pour cloisonner une application
#networks:
#  web-nw: