commonAnnotations:
  app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
  app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
  kubernetes.io/ingress.class: traefik

resources:
  - request-relay-ingressroute.yml
  # - data-certificate.yml
  - request-relay-headers-middleware.yml
  - request-relay-ratelimit-middleware.yml
  - request-relay-inflightreq-middleware.yml

#patchesStrategicMerge:
#  - web_nw_networkpolicy_namespaceselector.yml
